### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by PaceyIV** [vitalif/grive2#10]
I've compile grive2 without errors but when I run grive in my debian armhf board I always get the "Segmentation fault" error.

**Comment by vitalif** [comment]
Can you compile it with debug info, run under gdb and post a stack trace?

**Comment by PaceyIV** [comment]
I'm sorry, but now I can't get the error again.
I've install other libraries and package from debian and now grive works fine.
I can't give you some information about which libraries, package.

**Comment by vitalif** [comment]
Ok... I'll close it then...
