### ISSUE TITLE
compilation problem: libcurl.so: undefined reference to `...`

### ISSUE THREAD

**Issue by gorgitko** [vitalif/grive2#100]
Compilation stuck on 98 % when "Linking CXX executable grive". I get these errors:

``/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcurl.so: undefined reference to `SSL_CTX_new@OPENSSL_1.0.0\'``

and so on. Complete error log is here: http://pastebin.com/kwdVnUS7
It's probably some problem with openssl libraries, but I can't fix it :worried:

Thank you in advance for your help!

**Comment by vitalif** [comment]
probably your curl config flags reported by cmake miss openssl, or it's trying to link it with incorrect openssl version.
what's your linux distro?

**Comment by gorgitko** [comment]
Ubuntu 16.04 LTS

**Comment by gorgitko** [comment]
I figured it out myself:

`$ sudo apt-get install --reinstall libgnutls-openssl27 libcurl4-gnutls-dev`

Than it compiles without problem :)
Maybe `libgnutls-openssl27` is not needed, I just tried it before installing `libcurl4-gnutls-dev`
