### ISSUE TITLE
Is it possible to skip "Reading local directories" and begin uploading to drive immediately?

### ISSUE THREAD

**Issue by SEIKT** [vitalif/grive2#101]
As per title. Thanks.

**Comment by vitalif** [comment]
O_o
No. Grive first needs to find new files to upload anything. This is what is called "Reading local directories".

**Comment by SEIKT** [comment]
I understand. Thought there could be something that could re-coded so that Grive handles the uploading process differently as I've used Rclone and Drive and both clients start the upload process instantaneously.

**Comment by vitalif** [comment]
Do you mean your problem is that "reading local directories" takes too much time?

**Comment by SEIKT** [comment]
That would be correct. For instance "read local directories" hangs for 15 minutes on a 25GB file and for 45 minutes on a 80GB file.

**Comment by vitalif** [comment]
Yeah, it calculates checksums for new files...

**Comment by SEIKT** [comment]
Alrighty. So the process can't be changed to quicken the process and starts near instantly like rclone for example?

**Comment by cinquecento** [comment]
MD5 checksum elapsed time examples:
```
$ echo $SHELL
/bin/bash
$ TIMEFORMAT='MD5 checksum elapsed time: %0lR'

$ truncate -s 26843545600 25GB.file
$ time md5sum 25GB.file >/dev/null
MD5 checksum elapsed time: 0m55s

$ truncate -s 85899345920 80GB.file
$ time md5sum 80GB.file >/dev/null
MD5 checksum elapsed time: 3m38s
```
More cpu Mhz, faster it is.

**Comment by SEIKT** [comment]
I see. Yeah, my server has a terrible Atom CPU. I'm just wanting to one way sync (upload) files to Google drive. I've been using the "Grive -s" command. Is it necessary for the Grive2 to calculate checksums for new files? Is that method of doing things the only possible way Grive2 can upload files to Google Drive?

**Comment by vitalif** [comment]
grive uses md5 sums for 2 tasks:

1. determine which files are renamed locally to rename them server-side without re-uploading
2. determine which files are unchanged (calculating checksum is considered to be faster than upload)

So yes, it's possible to speed up things... (1) may be skipped if there are no deleted local files with the same size and (2) may be skipped if the file does not exist on server or has different size on server.

**Comment by SEIKT** [comment]
Understood. Well in my case I'm only uploading files that don't and have never existed on my Google Drive. So how would I go about skipping those two steps or is that automatically processed by Grive?

**Comment by rautamiekka** [comment]
MD5 ? Seriously ? At some point there'll be conflicts. SHA256 or preferably 512 should be used.

**Comment by vitalif** [comment]
> MD5 ? Seriously ? At some point there'll be conflicts. SHA256 or preferably 512 should be used.

say it to google :) https://developers.google.com/drive/v2/reference/files

**Comment by vitalif** [comment]
> Understood. Well in my case I'm only uploading files that don't and have never existed on my Google Drive. So how would I go about skipping those two steps or is that automatically processed by Grive?

Now it can't skip checksum calculation, it needs some code changes to work like this. I'll implement it when I have time

**Comment by SEIKT** [comment]
Champion, thanks.

**Comment by cinquecento** [comment]
For comparison,
MD5 checksum on NFS share (non cached - 1st run)

Speed: 1000Mb/s
```
$ time md5sum 25GB.file >/dev/null
MD5 checksum elapsed time: 3m48s

$ time md5sum 80GB.file >/dev/null
MD5 checksum elapsed time: 12m10s
```
Speed: 100Mb/s
```
$ time md5sum 25GB.file >/dev/null
MD5 checksum elapsed time: 38m2s

$ time md5sum 80GB.file >/dev/null
MD5 checksum elapsed time: 121m54s
```
Remotely - higher network throughput, faster it is.

**Comment by vitalif** [comment]
Done in master, please check...
