### ISSUE TITLE
Can't rebuild after checksum update

### ISSUE THREAD

**Issue by SEIKT** [vitalif/grive2#102]
Hey Vitaliy,

Getting this error when trying to build the latest version of grive. I have just attempted building the previous version of grive again and receive no errors.

[ 74%] Built target grive
Scanning dependencies of target grive_executable
Scanning dependencies of target btest
Scanning dependencies of target unittest
[ 75%] Building CXX object libgrive/CMakeFiles/btest.dir/test/btest/ValTest.cc.o
[ 77%] Building CXX object libgrive/CMakeFiles/btest.dir/test/btest/JsonValTest.cc.o
[ 79%] Building CXX object grive/CMakeFiles/grive_executable.dir/src/main.cc.o
[ 81%] Building CXX object libgrive/CMakeFiles/unittest.dir/test/UnitTest.cc.o
/home/james/grive2/libgrive/test/UnitTest.cc:24:30: fatal error: drive/EntryTest.hh: No such file or directory
compilation terminated.
libgrive/CMakeFiles/unittest.dir/build.make:62: recipe for target 'libgrive/CMakeFiles/unittest.dir/test/UnitTest.cc.o' failed
make[2]: *** [libgrive/CMakeFiles/unittest.dir/test/UnitTest.cc.o] Error 1
CMakeFiles/Makefile2:163: recipe for target 'libgrive/CMakeFiles/unittest.dir/all' failed
make[1]: *** [libgrive/CMakeFiles/unittest.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 82%] Building CXX object libgrive/CMakeFiles/btest.dir/test/btest/UnitTest.cc.o
[ 84%] Linking CXX executable btest
[ 84%] Built target btest
[ 86%] Linking CXX executable grive
[ 86%] Built target grive_executable
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by vitalif** [comment]
Rerun cmake or start with a clean build

**Comment by SEIKT** [comment]
Tried both solutions before creating this issue. Problem still persists.

**Comment by vitalif** [comment]
Oops. Just fixed, please retry
