### ISSUE TITLE
Error syncing - TCP connection reset by peer

### ISSUE THREAD

**Issue by cinquecento** [vitalif/grive2#111]
Running in the [screen](https://www.gnu.org/software/screen)
```
$ grive --debug --verbose --log [...] --log-http [...] -P --dir [...]
config file name "./.grive"
logging HTTP response: [...]
HTTP POST "https://accounts.google.com/o/oauth2/token"
HTTP response 200
Reading local directories
file [...] is ignored by grive
[...]
Reading remote server file list
HTTP GET "https://www.googleapis.com/drive/v2/files?maxResults=1000&q=trashed%3dfalse"
HTTP response 200
[...] is ignored by grive
[...]
Synchronizing files
sync "." already in sync
[...]
sync "[...]" doesn't exist in server, uploading
HTTP POST "https://www.googleapis.com/upload/drive/v2/files?uploadType=multipart&newRevision=false"
HTTP response 100===>                                                                                         ] 124.422 MB/1.083 GB
Error syncing "[...]": TCP connection reset by peer
Request URL: https://www.googleapis.com/upload/drive/v2/files?uploadType=multipart&newRevision=false
Request headers: Content-Type: multipart/related; boundary="file_contents"
Content-Length: 1162871093  
Authorization: Bearer [...]
GData-Version: 3.0

sync "[...]" doesn't exist in server, uploading
HTTP POST "https://www.googleapis.com/upload/drive/v2/files?uploadType=multipart&newRevision=false"
  [100%] [===================================================================================================>] 0.374 KB/0.374 KB
HTTP response 200
sync "[...]" doesn't exist in server, uploading
HTTP POST "https://www.googleapis.com/upload/drive/v2/files?uploadType=multipart&newRevision=false"
  [100%] [===================================================================================================>] 1.905 KB/1.905 KB
HTTP response 200
HTTP GET "https://www.googleapis.com/drive/v2/changes?maxResults=1&includeSubscribed=false&startChangeId=25032"
HTTP response 200
change stamp is set to 25039
Finished!
```

**Comment by vitalif** [comment]
Why do you think it's a bug? Does it reproduce every time?

**Comment by cinquecento** [comment]
Unfortunately it breaks all the time, at least here.

All command line tools should work without problems within the [GNU Screen](https://www.gnu.org/software/screen), including [Grive2](https://github.com/vitalif/grive2).
But what is the value here is, ***screen*** allows a user to detach (and reattach) sessions from a terminal, so a remote process - ***grive2*** continues running even when the user is disconnected.
***grive2*** cannot run in the background as system daemon, so the ***grive2 screen-ed*** is the most optimal "compensation" for a such functionality.

**Comment by vitalif** [comment]
Again, I don't understand. Isn't a "tcp connection reset by peer" some kind of a network error?

**Comment by rautamiekka** [comment]
Very easy googling answered that Google Drive sent you an ReSeT package which means they're dropping the connection here and now.

Just keep trying, it'll go through eventually, usually.

**Comment by vitalif** [comment]
Yeah, of course I know. But Google shouldn't drop connections on its own :) so it's probably caused by some network error. But if @cinquecento says it reproduces every time under certain conditions...
