### ISSUE TITLE
grive -a SingletonLock error

### ISSUE THREAD

**Issue by dmyersturnbull** [vitalif/grive2#113]
grive2.x86_64 0.5.0-4.20160114gitae06ecc.fc24 on Fedora 24.

```
grive -a
```

```
Please input the authentication code here: 
[...]
Reading local directories
exception: /builddir/build/BUILD/grive2-ae06eccb38b2fe250c9ddeac3e3973f80b8a0aa9/libgrive/src/util/OS.cc(57): Throw in function void gr::os::Stat(const string&, gr::DateTime*, off_t*, bool*)
Dynamic exception type: boost::exception_detail::clone_impl<gr::os::Error>
2, "No such file or directory"[boost::errinfo_file_name_*] = ./.config/google-chrome/SingletonLock
[boost::errinfo_api_function_*] = stat
```

Dependency versions are:
```
  boost-chrono.x86_64 1.60.0-7.fc24                                             
  boost-program-options.x86_64 1.60.0-7.fc24                                    
  boost-test.x86_64 1.60.0-7.fc24                                               
  boost-timer.x86_64 1.60.0-7.fc24              
```

**Comment by vitalif** [comment]
Are you trying to upload full home dir into google drive? Please don't :)

**Comment by dmyersturnbull** [comment]
@vitalif Would you mind explaining the error or pointing me to documentation?

There doesn't seem to be any usage documentation for grive 2: How is it supposed to be run? 

This is also a cryptic error message (which maybe should be replaced with something more helpful).

**Comment by vitalif** [comment]
Home directory contains a lot of garbage generated by various software: browser caches, open sqlite DBs, sockets, configs with cached passwords et cetera et cetera. Trying to upload these files into google drive is a bad idea...
Grive should be run from a separate directory dedicated for your google drive. I thought it was obvious, that's why I've not added into readme, OK, I'll add it.

**Comment by vitalif** [comment]
The error itself is caused by grive being unable to access ".config/google-chrome/SingletonLock" file. I don't know what this file is, but it's definitely something that shouldn't be uploaded into google drive.
