### ISSUE TITLE
grive and encfs

### ISSUE THREAD

**Issue by jjssoftware** [vitalif/grive2#138]
I'm trying to get this working to push files from a local encfs mounted volume to google drive. It appears as though this isn't possible because the grive program seems to want a .grive file containing a token to exist in the folder where the files to be pushed reside and this isn't the case for the encfs mounted volume - this encrypted volume only contains encrypted files.

I've built a shell script that contains something like this to create and mount the encfs volume:
```
SOURCE_FOLDER=/home/admin/datasync
TARGET_FOLDER=/home/admin/datasync-encrypted
PWD_FILE=/home/admin/encfs-password.sh

#unmount the encfs datasync-encrypted folder if mounted
if mountpoint -q -- $TARGET_FOLDER; then
    fusermount -u $TARGET_FOLDER
fi

#create the encfs encrypted view in $TARGET_FOLDER and mount it
encfs --extpass=$PWD_FILE --reverse $SOURCE_FOLDER $TARGET_FOLDER
```

Has anyone ever got something like this working with grive?

It seems as though it would be nice if the auth token could simply be passed to grive along with the source folder containing the files to push i.e. `/path/to/grive -t <TOKEN_GOES_HERE> -p /path/to/encfs_volume`

Cheers!
Joe

**Comment by vitalif** [comment]
What's the problem with encfs? does it differ from a regular fs?

**Comment by jjssoftware** [comment]
Yes an encfs volume works differently to a regular fs in a couple of ways:

1. As I mentioned in my first comment, an encfs mounted volume only contains encrypted files; in fact an encfs volume mounted with the --reverse option as demoed in my example is actually an "encrypted view" of the files and folders in some other plain text folder tree.
2. encfs mounted volumes do come with some limitations: since encfs is built on top of FUSE, one of the limitation of FUSE is that FUSE based filesystems are visible only to the user who mounted them. This normally won't be a problem since the user calling encfs will be the same user performing other operations on that volume e.g. using grive

It looks like grive code wants a .grive file containing a token to exist in the folder where the files to be pushed reside and this isn't the case for the encfs mounted volume - only encrypted files exist in the encfs volume.

Here's an example in pictures:

Consider this plain text folder tree:

![screenshot 2017-03-21 18 38 43](https://cloud.githubusercontent.com/assets/536164/24164442/a8cb2bd6-0e65-11e7-9bf0-5c482798bab0.png)

Now we can apply the encfs --reverse operation to the datasync-test folder with a command that looks like this:

`encfs --extpass=/home/admin/encfs-password.sh --reverse /home/admin/datasync-test /home/admin/datasync-test-encrypted/`

..and then having done that we now have an encrypted view of the files and folders in the original datasync-test in our datasync-test-encrypted folder:

![screenshot 2017-03-21 18 42 33](https://cloud.githubusercontent.com/assets/536164/24164599/2ba91cc0-0e66-11e7-9372-16c5e0d62c76.png)

You'd be right to assume that one of these 3 files in the datasync-test-encrypted folder is our .grive file but you can also clearly see that all of these files are encrypted.

This means that if we attempt to now do something like this:
`grive -p /volume1/home/admin/datasync-test-encrypted`

..we get a message back from grive that tells us:
`Please run grive with the "-a" option if this is the first time you're accessing your Google Drive!`

..which is why I believe that grive is looking for and expecting the .grive file to exist in the datasync-test-encrypted folder but it doesn't find it because although it's there, it's there in encrypted form.

I expect that if there was an option to be able to pass the auth token on the grive command line this would just work as expected.

**Comment by vitalif** [comment]
Why not just run `grive -a` initially from the encrypted folder?

**Comment by vitalif** [comment]
I.e do I understand correctly that real (not reverse emulated) encfs just stores encrypted files in some other dir which can be synced just as any normal dir?

**Comment by jjssoftware** [comment]
> Why not just run grive -a initially from the encrypted folder?

When this is attempted, encfs returns an Input/output error because the .grive file doesn't exist and it's not possible for grive to create a new .grive file directly in the encfs encrypted volume.

Some file operations are possible in the encrypted volume e.g. deletion of an existing encrypted file does work as expected but when this delete operation is performed, it's important to note that the non-encrypted file is also deleted from the plain text folder that the encrypted folder "mirrors".

Perhaps this better explains what I was trying to describe when I said that an encfs volume mounted with the --reverse option is actually an "encrypted view" of the files and folders in some other plain text folder tree.


> I.e do I understand correctly that real (not reverse emulated) encfs just stores encrypted files in some other dir which can be synced just as any normal dir?

Having had a little play with encfs without the --reverse option I think there maybe a workable solution here. I'll keep playing and report back.

**Comment by vitalif** [comment]
I suppose --reverse is a FUSE emulation of an encrypted dir, not a real encrypted dir, and that's why it's not directly writable, and real encfs storage should be writable without any problem. The only case is if encfs gives error for files which names it can't decode...or maybe it will decode it and show files with strange names for .grive and .grive_state in mount path...

But anyway, you may put the encrypted storage in a subdirectory of grive root and sync it from the upper path.

**Comment by jjssoftware** [comment]
In the end I settled on staying with the encfs --reverse option and doing what you suggested by sync'ing the encrypted data contained in a sub folder by executing grive from a non-encrypted parent folder.

**Comment by vitalif** [comment]
What about trying to run grive from the real encrypted dir? Does it succeed?

**Comment by jjssoftware** [comment]
I'm using the encfs --reverse option so I don't have a real encrypted directory, I just have a temporary encrypted view of my files prepared for google drive (and dropbox) push
