### ISSUE TITLE
infinite loop after refreshing token

### ISSUE THREAD

**Issue by TimKrause2** [vitalif/grive2#16]
After the token is refreshed grive keeps uploading the same file. Here is the output with the --debug flag specified. I'm using the latest revision.

HTTP PUT "https://www.googleapis.com/upload/drive/v2/files/0B4RChP-vlFkwb2pYb0VVNWJOTVE?uploadType=media"
HTTP response 401
request failed due to auth token expired: 401. refreshing token
HTTP PUT "https://www.googleapis.com/upload/drive/v2/files/0B4RChP-vlFkwb2pYb0VVNWJOTVE?uploadType=media"
HTTP response 401
request failed due to auth token expired: 401. refreshing token
HTTP PUT "https://www.googleapis.com/upload/drive/v2/files/0B4RChP-vlFkwb2pYb0VVNWJOTVE?uploadType=media"
HTTP response 401
request failed due to auth token expired: 401. refreshing token
HTTP PUT "https://www.googleapis.com/upload/drive/v2/files/0B4RChP-vlFkwb2pYb0VVNWJOTVE?uploadType=media"
HTTP response 401
request failed due to auth token expired: 401. refreshing token
HTTP PUT "https://www.googleapis.com/upload/drive/v2/files/0B4RChP-vlFkwb2pYb0VVNWJOTVE?uploadType=media"
HTTP response 401
request failed due to auth token expired: 401. refreshing token
HTTP PUT "https://www.googleapis.com/upload/drive/v2/files/0B4RChP-vlFkwb2pYb0VVNWJOTVE?uploadType=media"
^C

**Comment by vitalif** [comment]
Each file is uploaded with two requests: the first one saves metadata and the second uploads the file itself. Do you mean you got 401 error only for the second request?
Can you still reproduce it?
If yes, please retry with the latest version from master, I've made it print response body also on 401. I suspect the expired token may be not the case here and the real cause may be described in response body...

**Comment by TimKrause2** [comment]
Here is the output with the latest version and --debug specified

sync "./tmp/data06" doesn't exist in server, uploading
HTTP POST "https://www.googleapis.com/drive/v2/files" with "{"parents":[{"id":"0B4RChP-vlFkwdjVEdW56SDh6bmM"}],"title":"data06"}"
HTTP response 200
HTTP PUT "https://www.googleapis.com/upload/drive/v2/files/0B4RChP-vlFkwSndFM3Jjb2poTlE?uploadType=media"
HTTP response 401
request failed due to auth token expired: 401 (body: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "authError",
    "message": "Invalid Credentials",
    "locationType": "header",
    "location": "Authorization"
   }
  ],
  "code": 401,
  "message": "Invalid Credentials"
 }
}
). refreshing token
HTTP PUT "https://www.googleapis.com/upload/drive/v2/files/0B4RChP-vlFkwSndFM3Jjb2poTlE?uploadType=media"
HTTP response 401
request failed due to auth token expired: 401 (body: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "authError",
    "message": "Invalid Credentials",
    "locationType": "header",
    "location": "Authorization"
   }
  ],
  "code": 401,
  "message": "Invalid Credentials"
 }
}
). refreshing token
HTTP PUT "https://www.googleapis.com/upload/drive/v2/files/0B4RChP-vlFkwSndFM3Jjb2poTlE?uploadType=media"
^C

**Comment by vitalif** [comment]
Fixed it in #19. :-)
