### ISSUE TITLE
Installation not working on Ubuntu 17.10 due to binutils version 2.29.1

### ISSUE THREAD

**Issue by babjak** [vitalif/grive2#162]
$ sudo dpkg -i ./grive_0.5.1-1+git20170322-webupd8-zesty0_amd64.deb 
Selecting previously unselected package grive.
(Reading database ... 210574 files and directories currently installed.)
Preparing to unpack .../grive_0.5.1-1+git20170322-webupd8-zesty0_amd64.deb ...
Unpacking grive (0.5.1-1+git20170322~webupd8~zesty0) ...
dpkg: dependency problems prevent configuration of grive:
 grive depends on binutils (<< 2.29); however:
  Version of binutils on system is 2.29.1-4ubuntu1.

**Comment by callegar** [comment]
Ubuntu 17.10 is named artful. You are trying to install a binary package that was prepared for 17.04 (zesty). So the error is not completely unexpected. If you create your own deb file from source, following the instructions, it works perfectly in 17.10.

Alternatively, I think that you should report it to the maintainer of the webudp8 ubuntu ppa, not here.

**Comment by babjak** [comment]
I've created my own deb package as described in the instructions. I've installed and tested it, and it seems to be working fine.

Thank you!

**Comment by hippke** [comment]
I have the same problem. Can you explain to me how to solve it? I'm not sure I am competent enough to repackage my own deb

**Comment by babjak** [comment]
I think it's pretty straightforward, just look at this paragraph:
https://github.com/vitalif/grive2#install-dependencies
And then this one:
https://github.com/vitalif/grive2#build-debian-packages
