### ISSUE TITLE
Text entry only allows numerical 2, 6, 0

### ISSUE THREAD

**Issue by zhengqunkoo** [vitalif/grive2#174]
I'm running a Ubuntu 16.04, Keepass2 version 2.32+dfsg-1, Mono JIT compiler version 5.4.1.6.

Anywhere that requires text entry (e.g. Master Key, search bar, Title, User name, Password, Override default sequence) only supports the physical number keys 2, 6, 0, as located on the QWERTY keyboard.

Changing the firmware keyboard layout in Ubuntu (e.g. to Programmer Dvorak) only changes the output of those 2, 6, 0 keys, and other numerical keys remain unaccessible.

Alphabet is fine. I think I read somewhere this is a problem with Mono? But I didn't find any solutions.

**Comment by vitalif** [comment]
Is that related to grive?:)
