### ISSUE TITLE
[HELP] How to uninstall grive2

### ISSUE THREAD

**Issue by WangYihang** [vitalif/grive2#182]
Could you tell me how can I uninstall grive2 completely, I installed it form source code.
just like this:
```
mkdir build
cmake ..
make -j8
make install
```
But there is no argument for makefile, such as:
```
make uninstall
make remove
```
Thank you.

**Comment by WangYihang** [comment]
Can I just remove the following files? It that completely enough?
```
➜  build git:(master) make install
[ 88%] Built target grive
[ 96%] Built target btest
[100%] Built target grive_executable
Install the project...
-- Install configuration: ""
-- Up-to-date: /usr/local/lib/systemd/user/grive-changes@.service
-- Up-to-date: /usr/local/lib/systemd/user/grive-timer@.service
-- Up-to-date: /usr/local/lib/systemd/user/grive-timer@.timer
-- Up-to-date: /usr/local/lib/grive/grive-sync.sh
-- Up-to-date: /usr/local/bin/grive
-- Up-to-date: /usr/local/share/man/man1/grive.1
```

**Comment by beliys** [comment]
yes, but also can uninstall unnecessary dependencies

**Comment by vitalif** [comment]
I think yes. `cmake` does not generate `make uninstall` target by default, but all installed files are listed in `install_manifest.txt`

**Comment by WangYihang** [comment]
Okay, Got it, thank you so much! @beliys @vitalif
