### ISSUE TITLE
sync fails after install

### ISSUE THREAD

**Issue by mkauzlar** [vitalif/grive2#2]
Hello, I installed grive2 as per instructions (Mint 17 64bit)
After authentication the sync fails with:

Reading remote server file list
HTTP GET "https://www.googleapis.com/drive/v2/files?maxResults=1000&q=%27me%27+in+readers+and+trashed%3dfalse"
HTTP response 200
exception: /home/mkauzlar/Downloads/grive2-master/libgrive/src/json/Val.cc(90): Throw in function const gr::Val& gr::Val::operator[](const string&) const
Dynamic exception type: boost::exception_detail::clone_impl<gr::Val::Error>
[gr::NoKey*] = md5Checksum

**Comment by vitalif** [comment]
Hm. That means google returns a drive file without MD5 checksum in your case. What can that file be?... API docs says "An MD5 checksum for the content of this file. This is populated only for files with content stored in Drive"...

It seems google docs documents have no md5 checksum. Interesting...

**Comment by vitalif** [comment]
I've just fixed it by ignoring files without md5Checksum. That means google documents won't be synced, but drive should work overall...

**Comment by mkauzlar** [comment]
Working after this change however now is moving all files and folders to Trash in google drive.
Here is what I did:

Create local folder GDrive
cd GDrive
grive -a (and do all the auth)
starts syncing and all messages like this appears:

sync "./Folder" deleted in local. deleting remote 

Same with files.

In google drive I can see they are all moved to Trash

**Comment by vitalif** [comment]
Did you do it on a clean newly created directory, or in a directory in which grive was ran some time in the past? If there's a .grive_state with a changestamp greater than the last changestamp on the google side, but no local files, grive will think you deleted them and try to delete them server-side...

**Comment by mkauzlar** [comment]
Started from scratch and all is ok now. Must have been the .grive_state from the failed attempts before your fix.
Thanks
