### ISSUE TITLE
Got Rate Limit Exceeded

### ISSUE THREAD

**Issue by jonmartinsolaas** [vitalif/grive2#203]
[gr::http::ResponseBodyTag*] = {
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "rateLimitExceeded",
    "message": "Rate Limit Exceeded"
   }
  ],
  "code": 403,
  "message": "Rate Limit Exceeded"
 }
}

**Comment by pbackx** [comment]
Same problem for me. The same operation used to work about a month ago, so I'm guessing Google changed something.

Google suggests to use exponential backoff, but it does not look like something that's quickly done (I haven't looked into the Grive code):
https://developers.google.com/drive/api/v3/handle-errors#403_rate_limit_exceeded

**Comment by vitalif** [comment]
Why not quickly, it's a matter of few lines of code... I've just committed a fix. Please recheck if it helps. It tries to sleep for 1 second on error, then 2, 4 etc... up to 64 seconds and then for 120 seconds without increasing if it still gets errors.

**Comment by pbackx** [comment]
Thanks a lot for this, I didn't know it would be an easy fix.

**Comment by callegar** [comment]
I also see an issue with the "rate limit" working with today's master. Is the fix committed to master?
