### ISSUE TITLE
[Question] Sync to sub folder

### ISSUE THREAD

**Issue by pyromanci** [vitalif/grive2#210]
This is my first time using Grive. I want to use it as means to back up data. 

What i have on my linux machine right now is a structure like

/home/user1
/home/user2
/home/user3
...
/sharedData

What I want to do is store all of home in a folders inside the google drive folder /Server1/home  
Then the /sharedData folder into the google drive folder /Server1/sharedData
As well allowing for 2 way sync sync.

As i look at the wiki. I actually do not think i can do this set up. unless there are a large number of command line options that missing form the wiki.

**Comment by nodatahere** [comment]
As far as I'm aware, the best way to make this work under the current release would be to create a folder for the sync that matches the structure you want on the Google Drive account, like the following:
```
/Grive/Server1/home/user1
/Grive/Server1/home/user2
/Grive/Server1/home/user3
...
/Grive/Server1/sharedData
```
After making/moving the folders to the arrangement you'd like them to have in Google Drive, you can then create symlinks from each folder in `/Grive/Server1` to the corresponding location on the rest of the filesystem using 'ln -s'. This way, the paths you want to back up (ie, `/home/user1`) point to the corresponding linked folder (`/Grive/Server1/home/user1`) as if it were in both places, and Grive (which can't follow symlinks as of the last time I checked) backs them up under the hierarchy created in `/Grive`.

**Comment by shaansheikh** [comment]
do something like
    grive -p / -s /Server1/home
    grive -p / -s /Server1/sharedData

that should do the trick

**Comment by vitalif** [comment]
`-s subdir`
