### ISSUE TITLE
griveignore malfunction with new boost

### ISSUE THREAD

**Issue by Artox** [vitalif/grive2#217]
Hi there,
I noticed that on opensuse tumbleweed my griveignore turned mad matching only pdf files on first and second levels. 
However my griveignore is designed as a whitelist for a bunch of folders and *.pdf at root
This worked as expected in opensuse leap. The most obvious difference between those two systems is the boost library version.
For reference this is the griveignore:
```
*
!IMX
!Scores
!*.pdf
```
And this is the pattern in .grive_state:
`"ignore_regexp":"^(?!IMX|Scores|[^/]*\\.pdf)([^/]*)$"`

It looks identical to a working system, but it does not work as expected any more :(

Last known working: 1.65.1
First known broken: 1.67.0

EDIT: removed patch which did *not* work!!!

**Comment by vitalif** [comment]
Did you just install a new version? It could be affected by a change from PR #201

**Comment by Artox** [comment]
Yes indeed :( Thanks for pointing it out, and finding the problem! master works as expected on a dry-run :)
