### ISSUE TITLE
Running grive at home directory

### ISSUE THREAD

**Issue by Yemeen** [vitalif/grive2#224]
I get

Reading local directories
File ./.gnupg/S.gpg-agent.ssh is not a regular file or directory; skipping file
File ./.gnupg/S.gpg-agent is not a regular file or directory; skipping file
File ./.gnupg/S.gpg-agent.extra is not a regular file or directory; skipping file
File ./.gnupg/S.gpg-agent.browser is not a regular file or directory; skipping file
exception: boost::filesystem::directory_iterator::construct: Permission denied: "./.dbus"

I believe it is because grive is trying to upload my "./" directory, but I am unable to exclude this directory via the ignore command

**Comment by vitalif** [comment]
You probably shouldn't run grive in home dir.
Also there was a bug with griveignore in last versions which I fixed today - please update
