### ISSUE TITLE
Does not link properly when yajl is built from source

### ISSUE THREAD

**Issue by kmactavish** [vitalif/grive2#23]
On older systems (Ubuntu 12.04), yajl must be built from source. It compiles to libyajl.so and libyajl_s.a. Grive assumes that pkg_config will only find a static library, which is not the case here (.so is found by default).

**Comment by vitalif** [comment]
That's not grive, I just use pkg_check_modules() cmake macro and it just takes info from pkg-config. So if you end up with .a in YAJL_LIBRARIES that probably means your pkg-config tells so, and in this case it's the pkg-config file which should be fixed...

**Comment by vitalif** [comment]
I'll close this bug by now. If you still think it should be fixed in some way at the grive2 side, please provide more details about your pkg-config output for yajl.

**Comment by kmactavish** [comment]
Thanks for the help, just haven't had a chance to look back at this.
