### ISSUE TITLE
grive-sync.sh is not uploading detected changes.

### ISSUE THREAD

**Issue by tsiegleauq** [vitalif/grive2#231]
Detecting changes using `systemctl --user start grive-changes@$(systemd-escape google-drive).service` works. However, uploading them works not.

`systemctl --user status grive-changes@$(systemd-escape google-drive).service`
Will inform you that:
```
grive-sync.sh[10574]: Listening for changes in ~/google-drive/
grive-sync.sh[10574]: Need a directory name in the current users home directory as second argument. Aborting.
```

therefore, no changes are being made.

Reproduce:

- `mkdir ~/grive-test`
- `cd ~/grive-test`
- `grive -a` and do the usuall stuff
-  `systemctl --user start grive-changes@$(systemd-escape grive-test).service`
- `touch ~/grive-test/test-file.txt`
- `systemctl --user status grive-changes@$(systemd-escape grive-test).service` will show the error.

**Comment by jankatins** [comment]
My guess is that this is because the unescape happens twice in that case: it's started with the escaped version, the listens to the changes, but the call to sync then uses a unescaped version of the filename. 

```bash
λ systemd-escape --unescape $(systemd-escape --unescape $(systemd-escape grive-test))
grive/test
```
