### ISSUE TITLE
Daily Limit for Unauthenticated Use Exceeded.

### ISSUE THREAD

**Issue by amirvarasteh** [vitalif/grive2#236]
I got this error after the authentication with "grive -a":

```
{
"error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "dailyLimitExceededUnreg",
    "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
    "extendedHelp": "https://code.google.com/apis/console"
   }
  ],
  "code": 403,
  "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
}
}
```

**Comment by jankatins** [comment]
@amirvarasteh In #242 there is now a possibility to set the client id and secret in the .grive config so you can use your own configured oauth client credentials. It also includes instruction how to get theses credentials. I would appreciate if you could test these changes and see if they work in your cases.

**Comment by vitalif** [comment]
#287 fixed, so maybe this should go away too
