### ISSUE TITLE
timer not working when using transparent proxy

### ISSUE THREAD

**Issue by chrischdi** [vitalif/grive2#240]
Hi there,

I tried using the `/usr/lib/grive/grive-sync.sh` script from behind a proxy server.
It fails with the following error:
```
$ /usr/lib/grive/grive-sync.sh sync gdrive
Google drive server not reachable...
```

This is because the firewalls do not allow to ping.
There are rest api's used for the synchronization, I propose to use curl or maybe wget instead of ping (or fallback to ping if no curl or wget is available)

**Comment by jankatins** [comment]
I basically added that because I use it on a laptop and ping was the easiest way to verify if I have a internet connection. So using wget/curl whatever sounds good.

**Comment by chrischdi** [comment]
Stale :-)
