### ISSUE TITLE
bug: auto sync timer not working as expected because of infinite loop

### ISSUE THREAD

**Issue by vonvonhero** [vitalif/grive2#241]
Auto sync timer is set to 5 min by default in grive-timer@.timer.
I would like to increase this timer interval like 30 min, so I modify grive-timer@.timer.
However, it does not change auto sync interval.

I have checked /var/log/syslog and find that grive-sync.sh is executed continuously and never end even if "Sync of GoogleDrive done." message is shown.  Syncing is start again right after Sync done message, like below log captured.

Nov 29 13:01:52 ubuntu_backup systemd[1586]: Started Google drive sync.
Nov 29 13:01:52 ubuntu_backup grive-sync.sh[1912]: Syncing GoogleDrive...
....
Nov 29 13:05:38 ubuntu_backup grive-sync.sh[1912]: Sync of GoogleDrive done.
Nov 29 13:05:38 ubuntu_backup grive-sync.sh[1912]: Syncing GoogleDrive...
....

This is because there is a bug in /usr/local/lib/grive/grive-sync.sh.
There is infinite while loop in sync_directory( ).

	TIME_AT_START=0
	TIME_AT_END=1
	while [[ "${TIME_AT_START}" -lt "${TIME_AT_END}" ]]; do
	    echo "Syncing "${_directory}"..." 
	    TIME_AT_START="$(stat -c %Y "$LOCKFILE")"
	    
            ~~~~~

	    TIME_AT_END="$(stat -c %Y "$LOCKFILE")"
	    echo "Sync of "${_directory}" done." 
	done

As you can see above, TIME_AT_START is saved time when grive start synchronize and TIME_AT_END is saved time when grive complete synchronize.

while [[ "${TIME_AT_START}" -lt "${TIME_AT_END}" ]]; do
This while condition is always true because TIME_AT_START is always less than TIME_AT_END. 
TIME_AT_START < TIME_AT_END : This relation ship never change so there is no way to exit from this while loop.

So we should change something like below to exit this infinite while loop.

	TIME_AT_START=1
	TIME_AT_END=0
	while [[ "${TIME_AT_START}" -gt "${TIME_AT_END}" ]]; do
	    echo "Syncing "${_directory}"..." 
	    TIME_AT_START="$(stat -c %Y "$LOCKFILE")"
	    
            ~~~~~

	    TIME_AT_END="$(stat -c %Y "$LOCKFILE")"
	    echo "Sync of "${_directory}" done." 
	done

After modifying source code, auto sync feature is working as expected. Sync interval time setting in grive-timer@.timer is now active.

I hope you guys review this and give some useful feedback!

Thanks,

**Comment by jankatins** [comment]
This is correct. I will create a PR...

**Comment by jankatins** [comment]
[Sorry for the wrong first answer (now deleted), but IMO the current behaviour is correct]

> As you can see above, TIME_AT_START is saved time when grive start synchronize and TIME_AT_END is saved time when grive complete synchronize.

The `stat -c %Y ${LOCKFILE}` is not measuring the time at start/end but the file modification time of the lockfile. So as long as the lockfile isn't touched, these two values are the same and so the current check would leave the loop. If the script is called a second time, the modification time of the lockfile is changed and the end time is bigger and the loop continues.

On the other hand, there is a problem: if you sync something, you also change files, which means that the changes part will trigger a sync which will (as the sync is still ongoing) change the lockfile and therefore restart the sync. In the worst cases, each sync will change a new file and therefore retrigger the sync.

I suspect that the current behavior is triggered by the `.griveignore` treatment in triggering it: inotifywait does not exclude that file and therefore each sync will retrigger it. Can you change the inotifywait cal into this

```bash
		inotifywait -q -r -e modify,attrib,close_write,move,create,delete --exclude ".grive_state|.grive|.griveignore" "${_directory}" > /dev/null 2>&1 && ${SCRIPT} sync "${_directory}"
```

to see if that fixes the problem?

**Comment by jankatins** [comment]
Oh wait, it's even more complicated:

1. The timer calls the sync -> this sync is running and changes the .griveignore file
2. The changes script notices the change and starts sync again which changes the lockfile and exits
3. The running sync from 1) exists, sees the changed lockfile and starts again -> go back to 1)

So what needs to happen is the either
1.) the `inotifywait` call ignoring the `.griveignore`file or
2.) removing the griveignorefile handling in the sync script. (i.e..  revert https://github.com/vitalif/grive2/commit/b47dd70f35ff74362c7094a55123a1be2618e5be)

I really don't like the first option because changing the griveignore file is potentially a far reaching change to the repo and therefore should trigger a sync.

@psfloyd: Do you see any other way to handle the symlink problem in grive?

**Comment by psfloyd** [comment]
I agree with @jankatins. I would revert griveignore file handling in Sync.

I've been thinking of another way of ignoring symlinks with the exclude option from grive itself.

I'm new to this and still learning. That commit wasn't supposed to be merged and I didn't realize. I must have done something wrong when I made the Pull Request.

English is not my first language, so please ask if there is something unclear.

**Comment by jankatins** [comment]
@psfloyd Thanks for your fast reply. I submitted https://github.com/vitalif/grive2/pull/245 which reverts the commit. IMO the easiest way to have this kind of behavior would to add a small script which does it manually or once a day or so in your local environment.

**Comment by Jarvar04** [comment]
I have the same issue. More so with one computer over another. However, I've also noticed it seems like an endless loop that keeps re triggering the grive sync. If I don't stop it, the same few file seems to keep downloading/uploading repeatedly. I thought it was only me, but it seems like others are experiencing it to. Luckily I don't have a cap on my internet bandwidth or else it just keeps climbing if I don't put a stop to it.
