### ISSUE TITLE
libexpat-devel requred

### ISSUE THREAD

**Issue by tieugene** [vitalif/grive2#25]
Subj

**Comment by vitalif** [comment]
Soooo what? :)

**Comment by tieugene** [comment]
Expat. Devel. Required.
http://i.imgur.com/ClYVdQZ.png

**Comment by tieugene** [comment]
README.md:
"You need the following libraries:
- yajl
- libcurl
- libstdc++
- libgcrypt
- Boost (Boost filesystem and program_option are required)"

+expat

**Comment by vitalif** [comment]
OK, just added it into readme :)
