### ISSUE TITLE
Exception when initializing

### ISSUE THREAD

**Issue by bernd-wechner** [vitalif/grive2#27]
ran grive -a on a fresh LinuxMINT system and it asked for my auth key which I got following the link provided and entered then it crashed as follows:

Reading local directories
exception: boost::filesystem::status: Too many levels of symbolic links: "./.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents/.wine/drive_c/users/bernd/My Documents"

**Comment by vitalif** [comment]
Did you ran it in your home directory?
This means "upload the whole home directory to google drive", so it's good it crashed :)
The issue itself just means that grive does not ignore symbolic links and does not handle loops in symlinks.
Do you think it should ignore symlinks? I think it may be useful to create symlinks inside the synced folder...

**Comment by bernd-wechner** [comment]
Looks like you nailed it. Thanks for the response. But in answer and moving to the next step:

1) No it should most definitely not follow Symbolic links. They are not supported on a Google drive and so clearly should not be pseudo supported in the local mirror. Much rather they should be ignored and reported.

2) Ooops. I didn't even stop to think I had to tell it where my mirror was with the -p option! My only comment would be that it should most probably not take a default for -p and demand one so as to avoid errroneous use such as mine. Easy enough to specify -p . explicitly.

3) Having specified it started synching but aargh I noticed it was all goofed up and wrong! The path I'm pointing at is on an NTFS partition that has my Google drive folder on it, up to date, kept so by the Google Drive client on Windows 7. And so I sort of expect grive just to say, "thanks, all good". Instead it starts:

Reading local directories
Synchronizing folders
Reading remote server file list
Synchronizing files
sync "filename" doesn't exist in server, uploading
...

And proceeds to do this for every file and folder in the path. Panic, stop!

First comment:

a) a --dry-run should almost be the default as well on a first run where -a is demanded! 
b) I checked the Google drive on the web site and yep, there is weirdness going on.
For a file in my root I now have two copies, one with the .gsheet or .gdoc extension one without.
  e.g. "Code Of Conduct - Draft" and "Code Of Conduct - Draft.gdoc"
For a folder I have two identically named folders!
   e.g. "Agendas" and "Agendas"
Ouch.
c) I checked the mirror on another Windows 7 box and see:
For a file I see one with the expected name and one with (1) appended.
  e.g. "Code Of Conduct - Draft.gdoc" and "Code Of Conduct - Draft (1).gdoc"
For a folder the same:
   e.g. "Agendas" and "Agendas (1)"

Summary:

weirdness is afoot:
1) They should not be upsynching at all the message:

"doesn't exist in server"

is wrong, there's a bug (and typo as it is "on the server" not "in the server") These files and folders do exist on the server.

2) When uploading it forks and the fork is displayed differently on the web site and on the windows mirror but that is a Google issue not a grive issue. 

Main thing is I have to go manually fix my danged drive now, and if and when I finally get my Linux box stably configured may download the grive source and debug it. This is most unsatisfactory alas. And somehow the API seems perhaps to misleading grive or grive misusing it to get a false negative on existence! 

Cheers,

Bernd.

**Comment by bernd-wechner** [comment]
vitalif, I'm confused. I wanted to download the source to try and build this and fix it. But I looked and found this as well:

https://github.com/MasterSoft24/Grive2

What gives? Why are there two Grive2 projects. Can it get any more confusing? Will leave a note with MasterSoft24 as well.

**Comment by vitalif** [comment]
It's amusing... but there is a line in README:

This release is adopted fork of Vitaliy Filippov / vitalif at mail*ru grive2 repo (https://github.com/vitalif/grive2)

So it's a fork, but I don't really know what additional features are implemented in that fork.

**Comment by bernd-wechner** [comment]
vitalif, did you check the link? What are these projects:

https://github.com/MasterSoft24/Grive2             an apparent reimplementation of grive from 24 Sep 2014

https://github.com/MasterSoft24/grive2m          system tray support for the first prject above.
https://github.com/MasterSoft24/grive2-gui	   a GUI for the first project above.

Why are there two Grive2 projects, yours and that of MasterSoft24?

Why did you fork and not build on the original grive branch?

I've sent an email to match065 to test if he's alive and responding to emails, and nestal doesn't provide an email, and these are the guys in the Grive organization at:

https://github.com/Grive

which it would be ideal to see active developers like you and MasterSoft24 join and work on the product proper rather than forking independently and creating version confusion.

**Comment by vitalif** [comment]
> Why did you fork and not build on the original grive branch?
Because I couldn't contact nestal at that time. Of course developing in https://github.com/Grive would be the best, but how to do that?

> https://github.com/MasterSoft24/Grive2
This is fork of my fork. I don't know the purpose of creating it :)

**Comment by vitalif** [comment]
Checked out the differences between his version and mine, his version
- has --list option to produce file list from google drive
- has support for something like .exclude or .include or so (mine one now has --ignore regexp version in master)
- has some pieces of scary code :)

Again, I should be very grateful if you could help me to contact original authors and take control over https://github.com/Grive :)

**Comment by vitalif** [comment]
Oh, everything is clear now, MasterSoft24's Grive2 fork was created before I've implemented the new API. And then he merged in my repo.

I've also asked him to indicate that his version is his own fork.

**Comment by bernd-wechner** [comment]
Awesome. I've done a little legwork. I emailed matchman but I doubt he's reading. He has a profile here too:

https://plus.google.com/109583648881972789292/about

And I've send one message to one of the people who have him in a circle, but it's blowing out into a research job alas. So I've emailed github to ask if they can get a message to him explaining why, and if the have a policy on opening the door on dead organizations after an inactivity timeout. I mean it is seriously possible that the two people in that organzation have literally or figuratively died and github could act as executor of the organization ;-).

I can see form messages between you and MasterSoft24 that you're hoping to merge your two forks again? I hope so. Ideally Matchsofts's GUI and System Tray repositories can also be merged into on single grive2 repository. 

Can you confirm that you guys are aiming to do that? As if so, I'll wait till you're back together working on one fork rather than two before I fetch the source and try and build it and diagnose my issues.

Thanks for your attention Vitalif and I hope we can see a cooperative grive development stream emerging again. Because if I make any fixes I'd like to start from a definitive code base and have one to contribute the fixes to. Not add to a divergence of forks.

Regards,

Bernd.

**Comment by aspiers** [comment]
Just wanted to say a big thanks to you guys for all the effort in trying to re-converge this project on a single fork!  It's sadly rare to find that level of co-operative attitude on github, but it makes a big difference to the project's chances of long-term success.  I really hope it works out.

I'll be needing to start using grive over the next few months, so hopefully I can contribute a bit to development (or at least testing and bug reporting / triaging) at some point soon.

**Comment by vitalif** [comment]
I've only asked MasterSoft24 to note that his fork is a fork by now :) of course if he cleans the code up I can merge his features; or I can reimplement them if people likes them.

You are of course also always welcome to send pull requests :)

I've also written to github support, and they said:

> I'm afraid I can't give you control of another GitHub account. We have a name squatting policy that sometimes allows us to release inactive usernames but the Grive account does not meet that criteria.
>
> What I can do, if you would like, is pass along a message to one of the owners of the organisation. You could request that they give you control of the name or that they invite you into the organisation. If you like the idea of that, then please reply to me with a polite message you'd like passed along. Please note that I'll only be able to do this once.
>
> I'm sorry if this wasn't the response you were hoping for!

But it seems they'll just send him another email, so I'm not sure this will work.

**Comment by bernd-wechner** [comment]
They may have another email address or some more contact details that he didn't make public. There is a small chance. It seems a shame to have some of the effort he put into starting the project lost due to disappearance (I mean for example his website at: http://www.lbreda.com/grive/start and G+ page at https://plus.google.com/116411649000013553715).

Also I'd love to see MathSoft24and you collaborating and contributing to one branch not two.Let's hope he agrees.

If we can't find match065 I'm tempted to start a new organization, and invite you and Mathsoft23 to join it ;-), this time with an agreement we don't all disappear and at very least if we move on let other contributors join the organization to keep it alive ;-). It's easy enough to do a simple one! Just a thought.

**Comment by vitalif** [comment]
So we still couldn't contact original grive authors?

**Comment by oOZeVsOo** [comment]
Hello, thanks for your great work.
Do you plan to address the bug posted here about ".gdoc" and ".gsheet" files generated and uploaded for each google doc file on the server ?

As far as I can tell, it seems to be behaving like that:
- grive sees a google drive file on server
- it downloads it (file format gdoc or gsheet)
- it uploads it since it's a new file
=> you end up with two files on server: the real google doc file and a .gdoc or .gsheet useless copy.

Thank you very much.

**Comment by vitalif** [comment]
Oops, sorry, it seems I missed that bug. I think it should be posted as a separate issue because here it's lost in the middle of discussion :-)
