### ISSUE TITLE
Support for suppliyng different google API credentials at runtime

### ISSUE THREAD

**Issue by PhilPotter** [vitalif/grive2#278]
I realise this is pretty niche - currently I patch mine in before I build each time, but would there be any interest in accepting a pull request to implement optional flags (usable with -a) that take a client id and secret and store them in .grive to use at runtime?

If not supplied, the code would just use the default_id and default_secret. This would improve flexibility for people such as myself that actually change these credentials and supply their own. Assuming this would be desired functionality for upstream, I would be happy to implement and submit said request - thought I'd gauge the opinion of @vitalif before beginning the work though.

I look forward to your response, many thanks.

Regards,
Phil

**Comment by jankatins** [comment]
> implement optional flags (usable with -a) that take a client id and secret and store them in .grive to use at runtime?

This should be implemented in https://github.com/vitalif/grive2/pull/242
