### ISSUE TITLE
dotted folders are not ignored anymore

### ISSUE THREAD

**Issue by KONEY** [vitalif/grive2#28]
Tonight something strange happened when syncing with Grive2: the program downloaded from Drive all the folders with a dot in front, which it used to ignore before. I didn't change anything since I compiled Grive2 on my Banana-Pi, back in july so I suspect something has changed API-side, but I think it's worth mentioning here anyway.

**Comment by vitalif** [comment]
It was in the commit c15bfbe8bc93e4d59810a0c47225e98fd8269428 which I've merged from @visap fork of grive...

**Comment by vitalif** [comment]
Ok, I've just added --ignore regexp option in master, please checkout and test :)
