### ISSUE TITLE
dpkg-buildpackage => clear-sign failed: No secret key

### ISSUE THREAD

**Issue by sparcbr** [vitalif/grive2#282]
How to fix this? 

```
dpkg-deb: building package 'grive' in '../grive_0.5.1+git20160731_amd64.deb'.
dpkg-deb: building package 'grive-dbgsym' in 'debian/.debhelper/scratch-space/build-grive/grive-dbgsym_0.5.1+git20160731_amd64.deb'.
        Renaming grive-dbgsym_0.5.1+git20160731_amd64.deb to grive-dbgsym_0.5.1+git20160731_amd64.ddeb
 dpkg-genbuildinfo
 dpkg-genchanges  >../grive2_0.5.1+git20160731_amd64.changes
dpkg-genchanges: info: including full source code in upload
 dpkg-source --after-build grive2
dpkg-buildpackage: info: full upload; Debian-native package (full source is included)
 signfile grive2_0.5.1+git20160731.dsc
gpg: skipped "Vitaliy Filippov <vitalif@yourcmc.ru>": No secret key
gpg: dpkg-sign.lac_ZEKw/grive2_0.5.1+git20160731.dsc: clear-sign failed: No secret key

dpkg-buildpackage: error: failed to sign .dsc file
```

**Comment by sparcbr** [comment]
Not really a proper solution, but I just used checkinstall which in turn calls plain make instead of dpkg-buildpackage.
First change to build subdirectory created by the previous build command, which is probably something like: 
`cd obj-x86_64-linux-gnu`
Then use checkinstall, or make install.
```
sudo checkinstall
```
And follow the instructions if needed.
Voilá..

**Comment by vitalif** [comment]
Why do you need to fix it? It still makes deb packages, just install them with dpkg -i

**Comment by fikrillah** [comment]
hey, glad to see you here, i'm sorry to ask you this, but any plan on releasing new version?

**Comment by vitalif** [comment]
No plans currently, but PRs are welcome as usual :)

**Comment by jankatins** [comment]
This is a dpkg-buildpackage issue: I think it has a flag to not run the signing step.

**Comment by dmokreckiy** [comment]
Successfully built package with `dpkg-buildpackage -j4 --no-sign`.
Tested in Ubuntu 22.04.
