### ISSUE TITLE
Selective synch / .exclude file

### ISSUE THREAD

**Issue by j0nn0** [vitalif/grive2#29]
Do the .exclude and .include files work? What should the format be?

Please add information to man, or publish somehow, the format for creating .exclude file, so that one can selectively synch folders.

Can wildcards be used, to exclude contents of an entire directory/subdirectory? 

eg: e.g.

/My Drive/Photos/big/*
or
./Google Photos/*.jpg

Many thanks

**Comment by vitalif** [comment]
Where did you get the idea of using .exclude / .include files? grive never had support for them :)
Although I'm planning to implement something like this because you're not the only one asking :)

**Comment by j0nn0** [comment]
I wish I could remember, but I thought it was implemented with grive2. :-?

At this stage, is there any way to manage selective sync, other than by
using the -s switch?


*Jon Pienaar*

*================Doing stuff with words.*

Phone: +27 82 572 9696

Blog:     http://jomawrite.wordpress.com/
Skype:  @jonpienaar
Twitter:  j0nn0

**Comment by vitalif** [comment]
No, -s is currently the only way to do selective sync...

**Comment by j0nn0** [comment]
I'm not much of a programmer, not even bash, but there should be a way to do something like:

#! /bin/bash
for i in `cat .include` ; do
grive -s $i    
done;

That would take care of local directories. Not sure about new remote directories -- I guess that would have to be managed manually at least initially, and then subsequent syncs would depend on adding the new directory to the .include file?
What do you think?

**Comment by vitalif** [comment]
I had an idea of adding regexp exclude parameter recently... maybe "include" parameter should be also converted to regexp? Although with perl regexp it's simple to implement exclude via include or vice versa with --exclude '^(?!include1|include2|include3|...)'

**Comment by vitalif** [comment]
I've just added --ignore regexp option, please check the master branch.
