### ISSUE TITLE
Can't compile grive2 in debian sid (unstable)

### ISSUE THREAD

**Issue by sergiomendozza** [vitalif/grive2#298]
Hi.  Compilation of grive2 has always been successful until recently in debian sid (unstable).  A few days ago I got this when buiding a deb package with dpkg-buildpackage -j4:

/home/sergio/git/grive2/grive2/libgrive/src/bfd/SymbolInfo.cc: In static member function ‘static void gr::SymbolInfo::BacktraceInfo::Callback(bfd*, asection*, void*)’:
/home/sergio/git/grive2/grive2/libgrive/src/bfd/SymbolInfo.cc:121:16: error: ‘bfd_get_section_vma’ was not declared in this scope; did you mean ‘bfd_set_section_vma’?
  121 |  bfd_vma vma = bfd_get_section_vma(abfd, section);
      |                ^~~~~~~~~~~~~~~~~~~
      |                bfd_set_section_vma
/home/sergio/git/grive2/grive2/libgrive/src/bfd/SymbolInfo.cc:127:40: error: cannot convert ‘bfd*’ to ‘const asection*’ {aka ‘const bfd_section*’}
  127 |  bfd_size_type size = bfd_section_size(abfd, section);
      |                                        ^~~~
      |                                        |
      |                                        bfd*
In file included from /home/sergio/git/grive2/grive2/libgrive/src/bfd/SymbolInfo.cc:26:
/usr/include/bfd.h:1206:35: note:   initializing argument 1 of ‘bfd_size_type bfd_section_size(const asection*)’
 1206 | bfd_section_size (const asection *sec)
      |                   ~~~~~~~~~~~~~~~~^~~
make[3]: *** [libgrive/CMakeFiles/grive.dir/build.make:612: libgrive/CMakeFiles/grive.dir/src/bfd/SymbolInfo.cc.o] Error 1
make[3]: Leaving directory '/home/sergio/git/grive2/grive2/obj-x86_64-linux-gnu'
make[2]: *** [CMakeFiles/Makefile2:153: libgrive/CMakeFiles/grive.dir/all] Error 2
make[2]: Leaving directory '/home/sergio/git/grive2/grive2/obj-x86_64-linux-gnu'
make[1]: *** [Makefile:133: all] Error 2
make[1]: Leaving directory '/home/sergio/git/grive2/grive2/obj-x86_64-linux-gnu'
dh_auto_build: cd obj-x86_64-linux-gnu && make -j4 returned exit code 2
make: *** [debian/rules:4: build] Error 255
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2

Hope it can be fixed soon.

Cheers,

Sergio.

**Comment by peje66** [comment]
The following changes maks it compile:
    diff --git a/libgrive/src/bfd/SymbolInfo.cc b/libgrive/src/bfd/SymbolInfo.cc
    index 5876cc0..b0f7c96 100644
    --- a/libgrive/src/bfd/SymbolInfo.cc
    +++ b/libgrive/src/bfd/SymbolInfo.cc
    @@ -118,13 +118,13 @@ void SymbolInfo::BacktraceInfo::Callback( bfd *abfd, asection *section,
            if ((section->flags & SEC_ALLOC) == 0)
                    return ;
            
    -       bfd_vma vma = bfd_get_section_vma(abfd, section);
    +       bfd_vma vma = bfd_section_vma(section);
            
            unsigned long address = (unsigned long)(info->m_addr);
            if ( address < vma )
                    return;
            
    -       bfd_size_type size = bfd_section_size(abfd, section);
    +       bfd_size_type size = bfd_section_size(section);
            if ( address > (vma + size))
                    return ;

**Comment by sergiomendozza** [comment]
Excellent.  It does compile.  There's however now another problem at another level.  I can't connect to google drive.  Even if I start from zero, i.e. grive -a then google replies the following: 

Sign in with Google temporarily disabled for this app

This app has not been verified yet by Google in order to use Google Sign In.

**Comment by cowo78** [comment]
> The following changes maks it compile:
> diff --git a/libgrive/src/bfd/SymbolInfo.cc b/libgrive/src/bfd/SymbolInfo.cc
> ...

See also PR #299

**Comment by cowo78** [comment]
> Excellent. It does compile. There's however now another problem at another level. I can't connect to google drive. Even if I start from zero, i.e. grive -a then google replies the following:
> 
> Sign in with Google temporarily disabled for this app
> 
> This app has not been verified yet by Google in order to use Google Sign In.

See #287

**Comment by vitalif** [comment]
PR #299 merged, issue #287 fixed (grive2 got verification). I'm closing this one
