### ISSUE TITLE
/libgrive/src/json/Val.cc(90)

### ISSUE THREAD

**Issue by claenjoy** [vitalif/grive2#3]
grive --dry-run
Reading local directories
Synchronizing folders
Reading remote server file list
exception: /Downloads/grive2-815d0ea44ea49044106cbc2b6685b57f078b5e9a/libgrive/src/json/Val.cc(90): Throw in function const gr::Val& gr::Val::operator[](const string&) const
Dynamic exception type: N5boost16exception_detail10clone_implIN2gr3Val5ErrorEEE
[PN2gr4expt12BacktraceTagE] = #0 0x4fc7e9 :0 gr::Exception::Exception()
#1 0x4e042d :0 gr::Val::Error::Error()
#2 0x4df81b :0 gr::Val::operator[](std::string const&) const
#3 0x4d40aa :0 gr::v2::Entry2::Update(gr::Val const&)
#4 0x4d3784 :0 gr::v2::Entry2::Entry2(gr::Val const&)
#5 0x4d28bb :0 gr::v2::Feed2::GetNext(gr::http::Agent*)
#6 0x4bea98 :0 gr::Drive::DetectChanges()
#7 0x4a43e9 :0 Main(int, char**)
#8 0x4a4a14 :0 main
#9 0x7f0ab35aeec5 /lib/x86_64-linux-gnu/libc.so.6 __libc_start_main
#10 0x4a31a9 :0 _start

**Comment by vitalif** [comment]
There should be one more line, and it's most interesting... :)

**Comment by vitalif** [comment]
I mean after the backtrace... there are usually more lines with argument values. Can you post them here?

**Comment by claenjoy** [comment]
only thing I have is this :

"Reading local directories
Synchronizing folders
Reading remote server file list
exception: /home/XXXX/Downloads/grive2-815d0ea44ea49044106cbc2b6685b57f078b5e9a/libgrive/src/json/Val.cc(90): Throw in function const gr::Val& gr::Val::operator[](const string&) const
Dynamic exception type: N5boost16exception_detail10clone_implIN2gr3Val5ErrorEEE
[PN2gr4expt12BacktraceTagE] = #0 0x4fc7e9 :0 gr::Exception::Exception()
#1 0x4e042d :0 gr::Val::Error::Error()
#2 0x4df81b :0 gr::Val::operator[](std::string const&) const
#3 0x4d40aa :0 gr::v2::Entry2::Update(gr::Val const&)
#4 0x4d3784 :0 gr::v2::Entry2::Entry2(gr::Val const&)
#5 0x4d28bb :0 gr::v2::Feed2::GetNext(gr::http::Agent*)
#6 0x4bea98 :0 gr::Drive::DetectChanges()
#7 0x4a43e9 :0 Main(int, char**)
#8 0x4a4a14 :0 main
#9 0x7efc28410ec5 /lib/x86_64-linux-gnu/libc.so.6 __libc_start_main
#10 0x4a31a9 :0 _start

[PN2gr5NoKeyE] = md5Checksum
"

my folder is empty :)

**Comment by vitalif** [comment]
Try newer version from trunk, it's already fixed in #2

**Comment by claenjoy** [comment]
thanks a lot 
works download I changed file then run again 
grive -V:

sync "./XXXX/xxxx.xx1"  already in sync
sync "./XXXX/xxxx.xx2"  already in sync
sync ""./XXXX/xxxx.xx3"  already in sync
sync "./XXXX/fileIchange.mmm" changed in local. uploading
request failed with 412, retrying whole upload in 5s
request failed with 412, retrying whole upload in 5s
request failed with 412, retrying whole upload in 5s
request failed with 412, retrying whole upload in 5s
request failed with 412, retrying whole upload in 5s
request failed with 412, retrying whole upload in 5s
request failed with 412, retrying whole upload in 5s
request failed with 412, retrying whole upload in 5s
request failed with 412, retrying whole upload in 5s
request failed with 412, retrying whole upload in 5s
request failed with 412, retrying whole upload in 5s
request failed with 412, retrying whole upload in 5s
request failed with 412, retrying whole upload in 5s
request failed with 412, retrying whole upload in 5s
request failed with 412, retrying whole upload in 5s
