### ISSUE TITLE
Could not build when following instructions

### ISSUE THREAD

**Issue by bernd-wechner** [vitalif/grive2#30]
Not a big issue ;-). I was following the directions here:

http://yourcmc.ru/wiki/Grive2

but alas when I tried to build a missing library was reported: boost_unit_test_framework

I had done this as suggested:

sudo apt-get install git cmake build-essential libgcrypt11-dev libyajl-dev libboost-filesystem-dev libboost-program-options-dev libboost-regex-dev libcurl4-openssl-dev libexpat1-dev libcppunit-dev binutils-dev

Was easy fixed as I just installed libboost-all-dev and it worked. 

I couldn't be bothered working out which of the quidzillion boost packages contained the missing boost_unit_test_framework alas. So just installed all of boost. Seems worth recommending anyhow.

**Comment by vitalif** [comment]
ok, I've added libboost-all-dev
