### ISSUE TITLE
grive: error while loading shared libraries: libboost_filesystem.so.1.71.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ShaddaiSchelin** [vitalif/grive2#304]
I get this error while trying to run grive2

grive: error while loading shared libraries: libboost_filesystem.so.1.71.0: cannot open shared object file: No such file or directory

How do I fix this? Thanks!

**Comment by ShaddaiSchelin** [comment]
I got it.
The new version is 1.72, so I downgraded it to 1.71 and it works now!

**Comment by ShaddaiSchelin** [comment]
Well, when I downgraded this grive2 works but I can't open qbittorrent anymore.

**Comment by vitalif** [comment]
Rebuild it from source

**Comment by ShaddaiSchelin** [comment]
Ok will try that
Thanks!

**Comment by segatrade** [comment]
Same bug for me. Is it possible to release fresh grive version?
