### ISSUE TITLE
Sing-in Disabled

### ISSUE THREAD

**Issue by ghost** [vitalif/grive2#312]
Tried starting the program.
I get the below error:

"Sign in with Google temporarily disabled for this app
This app has not been verified yet by Google in order to use Google Sign In."

**Comment by Dishendramishra** [comment]
Check this out, I created some instructions with pictures.
https://github.com/Dishendramishra/linux-setup/blob/master/README.md#google-drive

**Comment by Dishendramishra** [comment]
> Tried starting the program.
> I get the below error:
> 
> "Sign in with Google temporarily disabled for this app
> This app has not been verified yet by Google in order to use Google Sign In."

Check this out, I created some instructions using pictures for resolving this.
https://github.com/Dishendramishra/linux-setup/blob/master/README.md#google-drive

**Comment by antwal** [comment]
> > Tried starting the program.
> > I get the below error:
> > "Sign in with Google temporarily disabled for this app
> > This app has not been verified yet by Google in order to use Google Sign In."
> 
> Check this out, I created some instructions using pictures for resolving this.
> https://github.com/Dishendramishra/linux-setup/blob/master/README.md#google-drive

Hi, 

command:

grive -a --id <secret-id> --secret <secret-code>

not working; after next command for sync ask run app with grive -a

Thanks.

**Comment by Dishendramishra** [comment]
> > > Tried starting the program.
> > > I get the below error:
> > > "Sign in with Google temporarily disabled for this app
> > > This app has not been verified yet by Google in order to use Google Sign In."
> > 
> > 
> > Check this out, I created some instructions using pictures for resolving this.
> > https://github.com/Dishendramishra/linux-setup/blob/master/README.md#google-drive
> 
> Hi,
> 
> command:
> 
> `grive -a --id <secret-id> --secret <secret-code>`
> 
> not working; after next command for sync ask run app with grive -a for complete registration
> 
> Thanks.

Could you please share your sequence of steps?

**Comment by antwal** [comment]
> https://github.com/Dishendramishra/linux-setup/blob/master/README.md#google-drive

Check screenshot
![grive](https://user-images.githubusercontent.com/410736/78064008-5c0c8d00-7391-11ea-8e7b-1eef1ab7977c.png)

**Comment by antwal** [comment]
Build now git latest version:

grive version 0.5.2-dev Mar 31 2020 19:11:28

now working; with the 0.5.1-dev not working.

**Comment by Dishendramishra** [comment]
> > https://github.com/Dishendramishra/linux-setup/blob/master/README.md#google-drive
> 
> Check screenshot
> ![grive](https://user-images.githubusercontent.com/410736/78064008-5c0c8d00-7391-11ea-8e7b-1eef1ab7977c.png)

secret-id and secret-code must be passed as strings.
```shell
grive -a --id "<secret-id>" --secret "<secret-code>"
```

**Comment by p-baum** [comment]
Intructions at https://github.com/Dishendramishra/linux-setup/blob/master/README.md#google-drive not working for me. I get the google screen:

> This app isn't verified
> This app hasn't been verified by Google yet. Only proceed if you know and trust the developer.
> If you’re the developer, submit a verification request to remove this screen. Learn more

**Comment by Dishendramishra** [comment]
> Intructions at https://github.com/Dishendramishra/linux-setup/blob/master/README.md#google-drive not working for me. I get the google screen:
> 
> > This app isn't verified
> > This app hasn't been verified by Google yet. Only proceed if you know and trust the developer.
> > If you’re the developer, submit a verification request to remove this screen. Learn more

ye you will get the google screen after  command below:
`grive -a --id "<secret-id>" --secret "<secret-code>"`

then you have to copy the code and paste in the terminal to start.

**Comment by antwal** [comment]
> Intructions at https://github.com/Dishendramishra/linux-setup/blob/master/README.md#google-drive not working for me. I get the google screen:
> 
> > This app isn't verified
> > This app hasn't been verified by Google yet. Only proceed if you know and trust the developer.
> > If you’re the developer, submit a verification request to remove this screen. Learn more

build 0.5.2 from git; with 0.5.1 not working also you use secret like string. no problem if app isn't verified

**Comment by p-baum** [comment]
Installed via arch AUR.

version: 520.ffb744a-1

**Comment by Dishendramishra** [comment]
> Installed via arch AUR.
> 
> version: 520.ffb744a-1
I am also using arch (manjaro linux).
I have created a video tutorial please check if you have missed anything.
https://www.youtube.com/watch?v=TzO8FyGu4U0

**Comment by Dishendramishra** [comment]
I created a GUI for grive2:
https://github.com/Dishendramishra/grive-gui
<img src="https://raw.githubusercontent.com/Dishendramishra/grive-gui/master/images/home.png">

**Comment by vitalif** [comment]
#287 fixed, grive2 got verification.
