### ISSUE TITLE
grive on multiple machines with same account: Must I authenticate again?

### ISSUE THREAD

**Issue by kaengo** [vitalif/grive2#317]
Hello!

On  my first Linux PC, grive2 runs since several years very fine. Thank you very much.
Now I tried to install it on a second Linux PC. 
I run grive -a on the second PC and use the link and 
gent an error:

Logging in with Google is temporarily disabled for this app; the use of Google Log-in has not yet been confirmed for this app.

Should I use the login-Data from the first machine?

Greetings,
Holger

**Comment by samikrc** [comment]
I think this is a recent change in the drive API behavior. Please follow the instructions available here to set it up as if you are doing it for the first time: https://github.com/vitalif/grive2#different-oauth2-client-to-workaround-over-quota-and-google-approval-issues

**Comment by Tatsh** [comment]
Related to #287

**Comment by vitalif** [comment]
#287 fixed, grive2 got verification.
