### ISSUE TITLE
An unending loop of get requests when trying to sync a folder with the google drive

### ISSUE THREAD

**Issue by mayankrungta** [vitalif/grive2#318]
Is the tool working currently? I don't see any updates for sometime on the repository and some flags that it may no longer work on threads like - [https://github.com/vitalif/grive2/issues/241](url). I have a simple requirement of a 80G folder remaining in sync with my local folder. If I move files around on the local setup it should sync on the google drive.

In attempting to do so I hit this loop which apparently is never ending as it looks like a repeat of get requests -

$ grive -V -d
config file name "./.grive"
HTTP POST "https://accounts.google.com/o/oauth2/token"
HTTP response 200
Reading local directories
file .grive is ignored by grive
Reading remote server file list
HTTP GET "https://www.googleapis.com/drive/v2/files?maxResults=999999999&q=trashed%3dfalse"
HTTP response 200
file "Folder A" is a google document, ignored
file "Folder B" is a google document, ignored
file "Folder C" is a google document, ignored
folder "./NestedTest" is created in remote
folder "./Test" is created in remote
HTTP GET "https://www.googleapis.com/drive/v2/files?maxResults=999999999&pageToken=~!!~XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&q=trashed%3Dfalse"
HTTP response 200
HTTP GET "https://www.googleapis.com/drive/v2/files?maxResults=999999999&pageToken=~!!XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&q=trashed%3Dfalse"
HTTP response 200
HTTP GET "https://www.googleapis.com/drive/v2/files?maxResults=999999999&pageToken=~!!~XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&q=trashed%3Dfalse"
HTTP response 200
.
.
.

Am I missing something or should I let this continue for a bit for the folder to sync. I have used  .driveignore to include -

`!Test$`

to include folders with Test in them. I tried using the command below without much luck -

`grive -d -s Test`

The Test folder currently contains only one single .txt file for the purpose of testing. I was hoping to test a nested folder next but no luck.

Please advise.

**Comment by Tatsh** [comment]
I am not having any problems with this. Maybe you are affected #308

**Comment by mayankrungta** [comment]
What do the repeated get requests mean? 30 seconds would be perhaps the length of time which it will wait for before giving up. Why is the sync not happening?

**Comment by Tatsh** [comment]
My fix puts a 30-second timeout on every HTTP request. I have had issues on my Mac where the Grive process hangs forever, and I am fairly the reason is lack of a timeout. Strangely, Google's servers don't signal a disconnect from their end after a long period of time.

**Comment by mayankrungta** [comment]
I tested again and it showed some activity of syncing after a point. It would be nice to see some kind of messages showing some progress.
