### ISSUE TITLE
Names file after "Current Version" instead of actual filename

### ISSUE THREAD

**Issue by smashnikov** [vitalif/grive2#32]
Hello,

I have started to use grive2. It is nice, but I believe I have found one bug.

Through Google's Windows and Mac client we are renaming files. They are also renamed through Googles Web App.

On ubuntu 14.04, we use grive2 for download, but then the filenames becomes incorrect.

Let's illustrate the behaviour with an example. 

This the filename in OS X: 

   5.Etagesteg--Etagesteg_i_massiv_ek.JPG

This is the filename on Ubuntu:

   P1000777.JPG

In the web app one can see that the "Current Version" is P1000777.JPG (refer to the attachment).
However I expect the filename to be the same as on Windows and OS X. Or?

$ grive --version
grive version 0.4.0-pre Sep 28 2015 09:02:25

Let me know if you need more details.

/Kind Regards 
L
<img width="521" alt="google_drive_web_app" src="https://cloud.githubusercontent.com/assets/14974703/10277335/9dc3e386-6b55-11e5-8e7e-418f80c27790.png">

**Comment by vitalif** [comment]
Can you please tell the exact scenario to reproduce this bug?
Do I understand correctly that it's like the following:
1) Create file in google drive
2) Rename it in WEB UI
3) Sync it with grive2 to a new folder and discover that it still has the old name
?

**Comment by smashnikov** [comment]
Hej,

Yeah, that is scenario.

1. On OS X: create the file 
# touch 1

2. On Web UI rename it to '2'

3. On OS X: google drive has synced and the filename is now '2'.

4. Issue grive on Ubuntu. The file is named '1.'  (both for a new folder and for the folder I had before the test started).

I also did a similar test with one difference. In step 2, the renaming was done through OS X Finder. After the sync, the new filename shows up in WEB UI. But 'grive -f' downloads it with the initial name. So rename does not need to be with WEB UI to recreate this issue.

**Comment by smashnikov** [comment]
Also don't know if it is relevant, but.

I am not the owner of the folder. I am allowed to edit, but i did not create it at first

**Comment by vitalif** [comment]
Ok, try the latest master... it seems "title" is the real filename, not "originalFilename".

**Comment by smashnikov** [comment]
I tried master. It works now as expected. Thanks!
