### ISSUE TITLE
app is blocked when trying 'grive -a' 

### ISSUE THREAD

**Issue by EhsanSarshar** [vitalif/grive2#332]
when I paste the link provided by 'grive -a' in the browser this error popup.

**This app is blocked
This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access.**

**Comment by mdeguzis** [comment]
Why is this closed? How did you solve it?

**Comment by EhsanSarshar** [comment]
this issue is resolved try to search in issues you can find the solution.
you should manually get the token from google drive
