### ISSUE TITLE
Google depricates "OAuth out-of-band (OOB) flow"

### ISSUE THREAD

**Issue by jankatins** [vitalif/grive2#362]
This at least affected my gdrive2 credentials which I added via the instruction in the readme. I haven't checked if there is a replacement flow which works with gdrive2.

The email:
```
Hello Google OAuth Developer,

We are writing to inform you that OAuth out-of-band (OOB) flow will be deprecated on October 3, 2022, to protect users from phishing and app impersonation attacks.

What do I need to know?
Starting October 3, 2022, we will block OOB requests to Google’s OAuth 2.0 authorization endpoint for existing clients. Apps using OOB in testing mode will not be affected. However, we strongly recommend you to migrate them to safer methods as these apps will be immediately blocked when switching to in production status.

Note: New OOB usage has already been disallowed since February 28, 2022.

Below are key dates for compliance

September 5, 2022: A user-facing warning message may be displayed to non-compliant OAuth requests
October 3, 2022: The OOB flow is blocked for all clients and users will see the error page.
Please check out our recent blog post about [Making Google OAuth interactions safer](https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html) for more information.

What do I need to do?
Migrate your app(s) to an appropriate alternative method by following these instructions:

Determine your app(s) client type from your Google Cloud project by following the client links below.
Migrate your app(s) to a more secure alternative method by following the instructions in the blog post above for your client type.
```

**Comment by vitalif** [comment]
Seems they want us to implement "loopback IP address flow". I may get to it if I have some spare time

**Comment by kierangrant** [comment]
Hopefully "loopback" flow will still work for native apps... as it is being disallowed as well for iOS, Android and Chrome apps...
https://developers.google.com/identity/protocols/oauth2/resources/loopback-migration

**Comment by bclarkx2** [comment]
@vitalif I wouldn't mind taking a crack at adding this. My approach would be:
1. Replace `redirect_uri=urn:ietf:wg:oauth:2.0:oob` with `redirect_url=http://localhost` in the authorization code and access token requests.
2. Use something like [cpprestsdk](https://github.com/microsoft/cpprestsdk) to listen on `localhost` and do two things: (A) receive the authorization code and pass it on to the rest of the auth code and (B) return a really simple web page that says "you can now close this browser".

Does that sound like a reasonable approach?

**Comment by bclarkx2** [comment]
By the way @vitalif I took a crack at this in https://github.com/vitalif/grive2/pull/369 and it seems to work alright. Apologies for my poor C++, though :sweat_smile:

**Comment by tom-ch1** [comment]
Thanks a lot, @bclarkx2, your patch #369 works for me.

**Comment by vitalif** [comment]
Lol. I implemented the same thing myself and looked at the PR only after that.
