### ISSUE TITLE
Can no longer authorize using client_id and client_secret

### ISSUE THREAD

**Issue by UlyssesZh** [vitalif/grive2#365]
After I try to go to the URL provided to get an authentication code, Google says
> Error 400: invalid_request
> You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy for keeping apps secure.
> You can let the app developer know that this app doesn't comply with one or more Google validation rules.

**Comment by thoraxe** [comment]
Is this possibly related to:
https://developers.google.com/identity/protocols/oauth2/resources/oob-migration

?

**Comment by UlyssesZh** [comment]
Yes.

**Comment by nick-robo** [comment]
@vitalif Any idea if this is fixable? I have `grive` working on a different laptop, but I can't get the authentication working here.

**Comment by Setinggil** [comment]
> @vitalif Any idea if this is fixable? I have `grive` working on a different laptop, but I can't get the authentication working here.

Me too

**Comment by vitalif** [comment]
Hi. Just implement the new auth flow, you can check it out.
