### ISSUE TITLE
Issue with initial sync

### ISSUE THREAD

**Issue by mwellerNVIH** [vitalif/grive2#372]
Howdy,

Running into this issue on a Debian 11 system trying to do the initial sync of my Drive with `grive -a`. It generates the auth URL, but the Google page says "Access blocked: grive2’s request is invalid".

Full error text from the page

Access blocked: grive2’s request is invalid
You can’t sign in because grive2 sent an invalid request. You can try again later, or contact the [developer](https://accounts.google.com/) about this issue. [Learn more about this error](https://support.google.com/accounts/answer/12379384)
If you are a developer of grive2, see [error details](https://accounts.google.com/).
Error 400: invalid_request

![image](https://user-images.githubusercontent.com/47873136/199628070-292864df-63be-4c67-be19-d0d77f49f3a5.png)

**Comment by Guangyun-Xu** [comment]
meet the same error
