### ISSUE TITLE
error while loading shared libraries: libsframe.so.0

### ISSUE THREAD

**Issue by wharvex** [vitalif/grive2#386]
When I run the "grive" command in my Google drive folder, it gives the following error:

> grive: error while loading shared libraries: libsframe.so.0: cannot open shared object file: No such file or directory

It had been working fine a couple days ago and I did not change anything in how I run the program or the program itself.

It also gives the same error message when I run grive in a non-grive directory (i.e. a directory without the .grive and .grive_state subdirectories).

Here are my grive version and system info.
grive version : 0.5.3-2
OS: Arch Linux
Kernel: x86_64 Linux 6.4.8-arch1-1

Please let me know if I should provide any additional information.

**Comment by funny0facer** [comment]
I had the same problem. Try removing grive and installing grive-git from the AUR. This worked for me.
As far as I understand, it has something to do with an ABI incompatible update of binutils. This is at least what I understood from a potential related bug. See https://bugs.archlinux.org/task/79278

**Comment by wharvex** [comment]
That worked for me, thank you! I will close the issue.
