### ISSUE TITLE
Grive2 not syncing local files

### ISSUE THREAD

**Issue by KONEY** [vitalif/grive2#42]
I'm trying to sync a specific folder (with new files in it) but grive states that that folder is being ignored. Nevertheless it is checking all the files form Drive, marking them as "parent doesn't exist, ignored" and not syncing anything of the new files.

Something wrong on my side or a bug?

Thanx

**Comment by vitalif** [comment]
What command do you use for that? grive -s?

**Comment by KONEY** [comment]
Forgive me for not providing it before. 

I invoke this batch:
#!/bin/bash
cd /mnt/nas/GOOGLE_DRIVE
./grive -s PHOTOZ/VARIE_2015 -d

so yes, -s

**Comment by KONEY** [comment]
is it wrong?

**Comment by vitalif** [comment]
I don't think it's wrong... but I haven't tested it with subdirectories, as well as with several calls to different subdirs as in #43 :)

**Comment by KONEY** [comment]
I see :) But let's say I try with just "-s PHOTOZ", I get the same problem... I can make another test anyway.

**Comment by vitalif** [comment]
I've just committed several -s / --ignore related fixes, try again with the latest version.
Also note that grive will remember the last value of -s / --ignore since now.
If you want to clear ignore regexp or -s value call grive with `grive --ignore ''`
