### ISSUE TITLE
Some files not synching

### ISSUE THREAD

**Issue by mikegilchrist** [vitalif/grive2#45]
I have just installed grive on two 14.04 machines using your private ppa and have gotten grive to sync with Google Drive.  However, there are files owned by me (but shared with others) in a my main folder and subfolders on Google Drive that aren't being synced to my local repository. THese include .docx and .xlsx files.

**Comment by vitalif** [comment]
Are these google docs? If yes it's a known limitation stated in readme: google docs are not synced by Grive.

**Comment by freedayko** [comment]
Seems problem with versioned files. When google drive contains the new version of file only second run of grive will syncing the file.

**Comment by mikegilchrist** [comment]
It was a google docs.  I didn't realize they were different than drive. Sorry for the naive question.

**Comment by vitalif** [comment]
> Seems problem with versioned files.

Checked it, grive seems to sync versioned files without problem now.
