### ISSUE TITLE
Google Documents downloading behavior

### ISSUE THREAD

**Issue by oOZeVsOo** [vitalif/grive2#48]
If you happen to have Google Documents on your drive, grive2 will download them as gdoc or gsheet files, instead of ignoring them.

As far as I can tell, it seems to be behaving like that:
1) grive sees a google drive file on server
2) it downloads it (creates file with format gdoc or gsheet)
3) it uploads it since it's a new file.
Finally, for each document, you end up with two files on server: the real google doc file and a .gdoc or .gsheet useless copy.

Thank you very much.

**Comment by vitalif** [comment]
I can't reproduce this bug on my account. Newly created google docs are not downloaded by grive at all in my case.
How did you create a google document triggering this bug?

**Comment by oOZeVsOo** [comment]
Another tool may have created those files and since the official client ignores them I was unaware of their existence before running grive.

I removed them all and it now works fine.

Thank you for your patience and for this nice piece of software.
