### ISSUE TITLE
Sub-subdirectory sync behavior

### ISSUE THREAD

**Issue by awan1** [vitalif/grive2#49]
It would be nice to be able to sync specific sub-subdirectories, e.g. 

    grive -s parent/child

and have grive create `parent/child` locally. Instead, it just fails, presumably since the `parent` folder hasn't been synced?

**Comment by j0nn0** [comment]
My understanding is it's perl style, so the syntax would be:
[cd to your Google drive]
**grive -s ./parent/child/**

[note the ./ for the relative path]

I am still hoping for the ability to make an exclude list, that allows for selective synching. This could be a plain text file that the grive command would automatically parse, and then automatically synch all folders and files that are not on the list. The list could include subdirectories, so for instance if, in your Google Drive folder (which could be anywhere you have read/write privileges) you have:
/Parent/child1/
/Parent/child2/
/Parent/child3/

If the .exclude file contains a line with:
*./Parent/child2*
then it will only synch ./Parent/child1 and ./Parent/child3

And the **-s** switch would override that, to allow for periodical manual override.

*Vitaly, I hope the above information is correct?????*
