### ISSUE TITLE
request failed with 412, retrying whole upload in 5s

### ISSUE THREAD

**Issue by claenjoy** [vitalif/grive2#5]
grive -V:

sync "./XXXX/xxxx.xx1" already in sync
sync "./XXXX/xxxx.xx2" already in sync
sync ""./XXXX/xxxx.xx3" already in sync
sync "./XXXX/fileIchange.mmm" changed in local. uploading
request failed with 412, retrying whole upload in 5s
request failed with 412, retrying whole upload in 5s
request failed with 412, retrying whole upload in 5s
request failed with 412, retrying whole upload in 5s
request failed with 412, retrying whole upload in 5s
request failed with 412, retrying whole upload in 5s
request failed with 412, retrying whole upload in 5s
request failed with 412, retrying whole upload in 5s
request failed with 412, retrying whole upload in 5s
request failed with 412, retrying whole upload in 5s
request failed with 412, retrying whole upload in 5s
request failed with 412, retrying whole upload in 5s
request failed with 412, retrying whole upload in 5s
request failed with 412, retrying whole upload in 5s
request failed with 412, retrying whole upload in 5s

**Comment by vitalif** [comment]
Try again...:)

**Comment by claenjoy** [comment]
yeo !!!
thansk a lot 
$: grive
Reading local directories
Synchronizing folders
Reading remote server file list
Detecting changes from last sync
Synchronizing files
Finished!"

Is it working also with the grive-tools ?

**Comment by vitalif** [comment]
I suggest you to retry from scratch, because it could've cached sync tinestamp which makes it think the directory is synchronized regardless of the error... :-)

**Comment by vitalif** [comment]
And what's grive-tools?

**Comment by claenjoy** [comment]
it is the indicator desktop icon 

https://launchpad.net/~thefanclub/+archive/ubuntu/grive-tools

**Comment by vitalif** [comment]
Since it just calls `grive` and `grive -a` I think yes, it should work...
Although I think running grive on every file change is a bit slow...

**Comment by claenjoy** [comment]
if there are some errors it should show the error not sync, right?

**Comment by vitalif** [comment]
Maybe, I didn't look into grive-tools code thoroughly

**Comment by xpro2004** [comment]
Same problem:
request failed with 412, retrying whole upload in 5s
request failed with 412, retrying whole upload in 5s
request failed with 412, retrying whole upload in 5s

Latest release installed.

**Comment by claenjoy** [comment]
im using this version   0.4.0-1~webupd8~utopic1	with this repository ppa:nilarimogard/webupd8 and 
with "grive -V" is working without error
