### ISSUE TITLE
Number of version issue

### ISSUE THREAD

**Issue by mslagmu** [vitalif/grive2#55]
In the 0.4.2 

#grive2 -v
Grive2 version 0.3 Jan  8 2016 07:59:20

**Comment by vitalif** [comment]
just checked 0.4.2:
$ git up v0.4.2
...
`HEAD is now at d2a6105... Release 0.4.2`
$ make -j4
...
$ grive/grive -v
`grive version 0.4.2 Jan  8 2016 11:32:54`

btw, why is your executable called grive2?

**Comment by mslagmu** [comment]
I'm sorry i made a error selecting my checkout

I 'm beginner with git
I use Hg

2016-01-08 9:36 GMT+01:00 Vitaliy Filippov <notifications@github.com>:

> just checked 0.4.2:
> $ git up v0.4.2
> ...
> HEAD is now at d2a6105... Release 0.4.2
> $ make -j4
> ...
> $ grive/grive -v
> grive version 0.4.2 Jan 8 2016 11:32:54
>
> btw, why is your executable called grive2?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vitalif/grive2/issues/55#issuecomment-169934537>.
>



-- 
Michel SLAGMULDER
17 rue Jean Lurcat
78210 Saint Cyr L'ecole

Tel :   33 1 34 60 26 29
Mob : 33 6 45 63 25 53
