### ISSUE TITLE
Option to delete files/folders without moving them to trash

### ISSUE THREAD

**Issue by albertdick** [vitalif/grive2#56]
I am using Grive with a backup script in a free Google Drive account.

The backup script runs daily and create a new local folder with backup contents, and simultaneously deletes a local backup folder created 7 days ago. After that, it's run Grive to synchronize changes. The local deleted folder is moved to trash folder in Google Drive, NOT freeing up the available space, and after some days, I get "The user has exceeded their Drive storage quota" message.

It would be very useful an option to remove files/folders from Google Drive without sending it to the trash folder (if technically possible).

**Comment by RobinManoli** [comment]
I would like this feature too!

**Comment by albertdick** [comment]
I don't know if that has been fixed, but after so many years, it doesn't matter anymore. There are better solutions than Google Drive for that purpose.
