### ISSUE TITLE
bandwidth feature and command line argument

### ISSUE THREAD

**Issue by atwskris** [vitalif/grive2#60]
It would be nice to be able to limit the bandwidth with a command line argument for grive2, as currently when using it, it maxes out our upload bandwidth (5mbps), and we can't use the internet for much other than web browsing and email.

If pointed in the right direction, I may be able to help with it, if shown some examples from other projects of code used to provide this functionality (at least I can try to help anyways).

**Comment by vitalif** [comment]
to implement this with curl you need CURLOPT_MAX_SEND_SPEED_LARGE and CURLOPT_MAX_RECV_SPEED_LARGE options.
but in fact until this is implemented you can try the universal hack for limiting bandwidth - `trickle` (userspace bandwidth limiter)
