### ISSUE TITLE
Data loss?

### ISSUE THREAD

**Issue by kamokr** [vitalif/grive2#64]
I think I just have lost a bunch of files and it happened within minutes after installing grive2. What I did:
1) synced Google Drive
2) moved a local folder with a lot of Google Documents among other files to another folder
3) synced again

It looks like grive2 just deleted the folder and reuploaded it, but without any Google Documents file, because they are not supported and they were not downloaded in the first place. Please somebody tell me these files aren't lost and can be recovered.

**Comment by rautamiekka** [comment]
If none of these apply, they're gone. I doubt asking Google would help either cuz they should get so much traffic it's likely the data is already overwritten:
- See if they're in Google Drive's trash section on the website
- You can try to use a deleted file recovery software specific to your filesystem, to recover to another drive/partition
- See your computer's trash folder

**Comment by kamokr** [comment]
They are not in Google Drive trash, and they were never present on my hard drive, so file recovery software or checking trash is pointless.

This is not good. I think I am starting to panic.

**Comment by kamokr** [comment]
It's fine. They are still present on a list of recently accessed files, even if I have accessed them months ago.

But I think people should be warned about this "feature" of grive2.

**Comment by vitalif** [comment]
Strange... They should really be in trash, because grive uses "trash" Drive API method to remove files and folders. If they're not present there it seems more like a "feature" of google drive itself...

**Comment by kamokr** [comment]
Here is what happened: the folder was indeed deleted and moved to trash, after recovering it it was empty, but after some time the files appeared.

So, fortunately, everything is fine. But I still think you should warn people about this, perhaps saving them from dying of a heart attack. Thanks for help!
