### ISSUE TITLE
Invalid grant

### ISSUE THREAD

**Issue by bmihaljevic** [vitalif/grive2#65]
Hi, 

I now get the following error when trying to sync. 

Failed to refresh auth token: HTTP 400, body: {
  "error" : "invalid_grant"
}
exception: /home/bmihalje/Downloads/grive2/libgrive/src/protocol/OAuth2.cc(116): Throw in function void gr::OAuth2::Refresh()
Dynamic exception type: boost::exception_detail::clone_impl<gr::OAuth2::AuthFailed>
[gr::expt::BacktraceTag*] = #0 0x51c88a :0 gr::Exception::Exception()
#1 0x4feadd :0 gr::OAuth2::AuthFailed::AuthFailed()
#2 0x4fe76c :0 gr::OAuth2::Refresh()
#3 0x4fd5a6 :0 gr::OAuth2::OAuth2(gr::http::Agent*, std::string const&, std::string const&, std::string const&)
#4 0x4b52c3 :0 Main(int, char**)
#5 0x4b59af :0 main
#6 0x7fc34fc57ec5 /lib/x86_64-linux-gnu/libc.so.6 __libc_start_main
#7 0x4b3ff9 :0 _start

Do you have any ideas what the problem might be? 

Thank you.

**Comment by redjamesg** [comment]
Last time I saw that, I had to delete the .grive and .grive-status and let it sync all over with the exchange of grant permission.

**Comment by vitalif** [comment]
Try `grive -a`

**Comment by bmihaljevic** [comment]
Thanks, @redjamesg , that solved it! 

I had already been trying with `grive -a` but that was not fixing it.

**Comment by rdh61** [comment]
@redjamesg, bmihaljevic,

Where are .grive and .grive-status? Can't find them!

Thank you.

**Comment by j0nn0** [comment]
They are created in your base GDrive (wherever you have decided that to be) when you first run grive. So  e.g. if your GDrive is ~/GoogleDrive, then when you run grive -a you **must** first cd to ~/GoogleDrive and run it from there (in terminal.) Then, you will find .grive and .grive-status there. You must be owner of the GDrive, so best to put it in your home or a partition that you own. Do you have the latest stable version? Maybe recompile/reinstall.

**Comment by rdh61** [comment]
Thank you @j0nn0. I deleted those to files, ran grive -a, and now grive is working for me again.

**Comment by tscloud** [comment]
I have a similar situation but slightly different stack trace.  Running version:
grive version 0.5.1-dev Oct 13 2016 12:07:36
I do not have .grive-status but do have .grive-state.  Should I delete .grive and .grive-state?

**Comment by savanna** [comment]
I ran into the same issue.  I only removed .grive file and re-run grive -a that fixed the problem.  Still curious why it didn't work without removing .grive file though.
