### ISSUE TITLE
partial syncing not working when / appended to folder name

### ISSUE THREAD

**Issue by oligu** [vitalif/grive2#68]
`grive -s afolder/`
only outputs
```
Reading local directories
Synchronizing folders
Reading remote server file list
Synchronizing files
Finished!
```
but does not sync anything. but 
`grive -s afolder`
without the trailing /, works perfectly. Adding a / comes quite naturally, as completing the name of the folder by pressing the tab button automatically adds it.

This might be related to #62.

**Comment by l0010o0001l** [comment]
I second this. @oligu: Unsure if you are aware (may be helpful), if you `grive -s <folder>` it will detect any sub-directories and subsequent files and upload them.

**Comment by vitalif** [comment]
I can't reproduce it, and in fact it's very strange because trim_path is there since the very beginning (libgrive/src/base/State.cc:48)
Even `grive -s /test/` works in my case...
