### ISSUE TITLE
Force only to upload files but not download the extra files in remote

### ISSUE THREAD

**Issue by realdmitchell** [vitalif/grive2#69]
Is it possible to add an option like "--only-upload" so that remote files missing locally would be skipped (not redownloaded) and only new local files will be uploaded. I am using it in a linux reinstalled chromebook with just 16 GB hdd. So I like to regularly upload only my new stuff; and delete files here.
Thanks for your great work!

**Comment by adaur** [comment]
I need the same thing for my PC: send new files to Google Drive, but do not download old ones if they are missing.

**Comment by adaur** [comment]
Awesome!
