### ISSUE TITLE
Error after input authetication key

### ISSUE THREAD

**Issue by adthonb** [vitalif/grive2#70]
Hello

I try to use grive2 but I can't pass the verification step. After I input key from google, I got this error.

> Please input the authentication code here:
> SOMEKEY
> exception: /build/grive2-3WknWe/grive2-0.5/libgrive/src/util/File.cc(128): Throw in function void gr::File::Open(const boost::filesystem::path&, int, int)
> Dynamic exception type: boost::exception_detail::clone_impl<gr::File::Error>
> [gr::expt::BacktraceTag*] = #0 0x812afe6 grive gr::Exception::Exception()
> #1 0x812d40a grive gr::File::Error::Error()
> #2 0x812c8df grive gr::File::Open(boost::filesystem::path const&, int, int)
> #3 0x812c9cf grive gr::File::OpenForWrite(boost::filesystem::path const&, int)
> #4 0x812c744 grive gr::File::File(boost::filesystem::path const&, int)
> #5 0x8132f25 grive gr::Config::Save()
> #6 0x80e7031 grive Main(int, char**)
> #7 0x80e7d7f grive main
> #8 0xb71a5a83 /lib/i386-linux-gnu/libc.so.6 __libc_start_main
> #9 0x80e5db1 grive
> 
> 13, "Permission denied"[boost::errinfo_file_name_*] = ./.grive
> [boost::errinfo_api_function_*] = open

I can use this before on same vps but now I can't

**Comment by vitalif** [comment]
This is a "Permission denied", check your file permissions :-)
