### ISSUE TITLE
Could not resolve host: accounts.google.com

### ISSUE THREAD

**Issue by FraYoshi** [vitalif/grive2#72]
I'm trying to link the "google for work" version of drive,
grive successfully installed, authenticated by token [-a] but It gives me back this error:

```
[gr::http::CurlCodeTag*] = 6
[gr::http::CurlErrMsgTag*] = Could not resolve host: accounts.google.com
[gr::http::RequestHeadersTag*] = Content-Type: application/x-www-form-urlencoded

[gr::http::UrlTag*] = https://accounts.google.com/o/oauth2/token
```

**Comment by vitalif** [comment]
This error means your computer can't find accounts.google.com O_o do you have no internet access? :D

**Comment by FraYoshi** [comment]
hahah I have a very slow and unstable internet access but I'm online :') In Italy it is like this..

anyway, the error appears trying to get the authentication!
I give the grant and paste the code on terminal but I immediately get this error message back:

---
`Please input the authentication code here: 
x/xxxxxxxxxxxxxxxxxxxxxxxxxxx

Failed to refresh auth token: HTTP 400, body: {
  "error" : "invalid_grant"
}
exception: path/to/the/folder/grive2/libgrive/src/protocol/OAuth2.cc(116): Throw in function void gr::OAuth2::Refresh()
Dynamic exception type: boost::exception_detail::clone_impl<gr::OAuth2::AuthFailed>
[gr::expt::BacktraceTag*] = #0 0x5383a9 :0 gr::Exception::Exception()
#1 0x51f4ef :0 gr::OAuth2::AuthFailed::AuthFailed()
#2 0x51f12b :0 gr::OAuth2::Refresh()
#3 0x51df2a :0 gr::OAuth2::OAuth2(gr::http::Agent*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
#4 0x4d2e89 :0 Main(int, char**)
#5 0x4d35a9 :0 main
#6 0x7ffb3439b830 /lib/x86_64-linux-gnu/libc.so.6 __libc_start_main
#7 0x4d1b79 :0 _start`

---
Do you think I am wrong in something or It is because of the google for work thing?

**Comment by vitalif** [comment]
I can't really say anything about google for work... so it may be related... but it also may be unrelated... try to sync your system time to an NTP server? A time skew sometimes results in invalid_grants...

**Comment by FraYoshi** [comment]
I tried more than a solution but nothing... but trying with another internet link, It worked! It just needed an initial push to start, now works with my very slow internet connection too ;) even if It stops many times and gives this error back

`request failed due to auth token expired: 401 (body: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "authError",
    "message": "Invalid Credentials",
    "locationType": "header",
    "location": "Authorization"
   }
  ],
  "code": 401,
  "message": "Invalid Credentials"
 }
}
). refreshing token
`

**Comment by vitalif** [comment]
so everything is ok now?

**Comment by FraYoshi** [comment]
It needs almost 15/20 minutes before starting to sync for reading local and remote files but It now works! Thanks for support :)
