### ISSUE TITLE
Problem when dual-booting

### ISSUE THREAD

**Issue by MangoMango666** [vitalif/grive2#76]
Hello.

I am trying to use Grive2 on a computer that has a dual-boot Windows 7 and Linux Mint and using the same folder for the files.
That means that two different pieces of software have to be able to synchronize the same folder : Grive2 when I am booting on Linux and the official Windows GD client.
In my case, the used folder was created in Windows by the GD client and used during over a year, with thousands of files. I later tried to synchronize it with Grive 2 under Linux.

Globally, it works but there are issues due to the fact that Grive 2 was never thought for this: 
 - The _desktop.ini_ files created in each folder and sub-folder under Windows for the customization of the appearance of the folders find themselves being uploaded to the GD server. It is then possible to delete them but then the folders loose their customized appearance in Windows. It might have other side-effects but I have seen them so far.
 - Similarly, there is an issue with the Google Docs files (.gsheet, .gform, etc.). The Windows GD client downloads and manages them, but Grive 2 is designed to simply ignore them .. when they are created on the GD server. Indeed, after starting Grive 2 for the first time, it tried to upload all the Google Docs files that were present on the hard drive - and succeeded to it, renaming them by adding a '(1)' at the end of their names since there already were files with these names on the GD server.

These two problems could be easily avoided by adding patterns to an exclude path ('desktop.ini' and all the file extensions that are typical of Google Docs).
More generally speaking, being able to add exclude paths would be great, it would also help excluding temporary files (which is actually a lacking feature in GD Windows client).

**Comment by vitalif** [comment]
You can easily solve it by using ignore regexp: `--ignore 'desktop\.ini$|\.gsheet$|\.gdoc$'`

By the way, what are these .gdoc, .gsheet and etc files inside?

**Comment by MangoMango666** [comment]
Hello.
Thanks for the advice. I had not seen that there is such an option in the manual of Grive2 ('man' command in Linux).
I tried  the command ` grive --dry-run --ignore 'desktop\.ini$|\.gsheet$|\.gdoc$'
but it seems to ignore the exclusion pattern.

**Comment by vitalif** [comment]
You're using an old version. 0.4.2-pre version marker was removed in january :-) try with the latest master

**Comment by MangoMango666** [comment]
Hello.
Actually, this is funny : the command `grive --version` says that I have version 0.4.2 installed but Synaptic says it is version `0.5-1+git20160516~webupd8~trusty`
Which one should I believe ? Most probably what the command says since it is the one I am running during operations, I guess.

**Comment by vitalif** [comment]
Remove one in /usr/local

**Comment by MangoMango666** [comment]
Hello.

Thanks for helping.

My problem is that I cannot find the where  the 0.5-1 version is installed.
The version in /usr/bin is the 0.4.2

I have tried to find where is the other version with a _find_ command :
`/usr/bin $ sudo find / -name '*grive*'
/usr/share/man/man1/grive.1.gz
/usr/share/doc/grive
/usr/bin/grive
/media/WINDOWS/Users/Me/Google Drive/.grive
/media/WINDOWS/Users/Me/Google Drive/.grive_state
/home/me/Grive/.grive
/home/me/Grive/.grive_state
/var/lib/dpkg/info/grive.list
/var/lib/dpkg/info/grive.md5sums
/var/cache/apt/archives/grive_0.5-1+git20160516~webupd8~trusty_amd64.deb
`
There is nothing in /usr/local.

As PPA for Grive2, I use `deb http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu trusty main`. Is it correct ?
When I download and try to install the .deb package from http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu/pool/main/g/grive2/  (this one : http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu/pool/main/g/grive2/grive_0.5-1+git20160516~webupd8~trusty_amd64.deb), it says that it is already installed.

So, somehow, it looks like the installed version 0.5-1 IS the 0.4.2. 
I admit I don't fully understand.

**Comment by vitalif** [comment]
It's a bad PPA then. File them a bug - they're packaging an old version.
You can build the package by yourself - just download the code from github and say `dpkg-buildpackage -j4` in the source directory.

**Comment by MangoMango666** [comment]
Hello.
I have created the .deb packages, although I had warnings due toseveral unmet dependencies : 
`dpkg-checkbuilddeps: Unmet build dependencies: libstdc++6-4.4-dev | libstdc++-4.9-dev | libstdc++-5-dev` 
I ignored them and creation of the packages seems to have gone fine. 

I have installed the package and I am testing it.

Thanks !

**Comment by vitalif** [comment]
do you have libstdc++-6-dev installed? I think I should add it to debian/control

**Comment by MangoMango666** [comment]
Hi again.

According to Synaptic, I have it no installed.
Synaptic lists libstdc++-6.4.7-dev as well as lib32stdc++-6.4.7-dev.
This library is necessary for runtime ?

**Comment by vitalif** [comment]
No, it's needed for build.
Ok, I've added it as an option to debian/control, so dpkg-buildpackage shouldn't complain anymore.
