### ISSUE TITLE
Trouble uploading files with latest 0.5.1-dev

### ISSUE THREAD

**Issue by adaur** [vitalif/grive2#81]
Hello,

I love Grive2 and I use it daily. However, I tried the latest version and I have not been able to upload files larger than a few kb (worked well with 1-2kb files, not with 60kb and larger). Anytime I launched the "grive" command, Grive would freeze saying : 

sync "./myfile" doesn't exist in server, uploading

If I enable the verbose mode, it would display the HTTP POST request but nothing more. The file was not uploaded in my Google Drive, obviously.

I reverted to v0.5.0 and everything worked well. I use Debian and I installed Grive with the commands from the readme.

**Comment by galenhuntington** [comment]
I'm on Ubuntu Trusty and also had this problem.  I was trying to diagnose it since I thought it might be my network setup, but I'm apparently not the only one.

Basically, the first 16K gets sent across the wire, then grive sits and stalls.  I did an strace, and it gets stuck here:

```
poll(0, 0, 4)                           = 0 (Timeout)
poll(0, 0, 8)                           = 0 (Timeout)
poll(0, 0, 16)                          = 0 (Timeout)
poll(0, 0, 32)                          = 0 (Timeout)
poll(0, 0, 64)                          = 0 (Timeout)
poll(0, 0, 128)                         = 0 (Timeout)
poll(0, 0, 256)                         = 0 (Timeout)
poll(0, 0, 1000)                        = 0 (Timeout)
poll(0, 0, 1000)                        = 0 (Timeout)
poll(0, 0, 1000)                        = 0 (Timeout)
poll(0, 0, 1000)                        = 0 (Timeout)
poll(0, 0, 1000)                        = 0 (Timeout)
poll(0, 0, 1000)                        = 0 (Timeout)
poll(0, 0, 1000)                        = 0 (Timeout)
```

Those go on for hours.  Finally it does seem to push another 16K, then go back to the timeouts, and some point after that the transaction fails.

Various errors are reported to the console, the most common being `SSL_write() returned SYSCALL, errno = 32`.  Others include the same with errno 22 or 110, or `Empty reply from server`.

Eventually the auth token expires and the whole sync terminates.

That's as far as I got.  Reverting to v0.5.0 made everything work again.

**Comment by xherbie** [comment]
Same here with v0.5.1-dev

**Comment by vitalif** [comment]
Interesting. Maybe it's setting curl speed limit to 0 when no option is passed? Try to call 0.5.1 with -U 10000 -D 10000

**Comment by vitalif** [comment]
No, I've checked, it's not the case.
Maybe it's related to the problem of build in PPA that you're using?
Are you all using the same PPA?

**Comment by xherbie** [comment]
2016-06-30 12:21 GMT+02:00 Vitaliy Filippov <notifications@github.com>:

> No, I've checked, it's not the case.
> Maybe it's related to the problem of build in PPA that you're using?
> Are you all using the same PPA?
>

I compiled from git.

Regards

**Comment by vitalif** [comment]
And you're still experiencing this issue?

**Comment by xherbie** [comment]
I went back to 0.5.0. But I try it tomorrow and I will give you a feedback.

Best regards

2016-06-30 12:50 GMT+02:00 Vitaliy Filippov <notifications@github.com>:

**Comment by cinquecento** [comment]
Set default value for download and upload speed to 10000  kbytes per second
```
---
 grive/src/main.cc | 9 +++++++++
 1 file changed, 9 insertions(+)

diff --git a/grive/src/main.cc b/grive/src/main.cc
index 477825f..3eec387 100644
--- a/grive/src/main.cc
+++ b/grive/src/main.cc
@@ -198,9 +198,18 @@ int Main( int argc, char **argv )
 	v2::Syncer2 syncer( &agent );
 
 	if ( vm.count( "upload-speed" ) > 0 )
+	{
 		agent.SetUploadSpeed( vm["upload-speed"].as<unsigned>() * 1000 );
+	}
+	else
+		agent.SetUploadSpeed( 10000 * 1000 );
+
 	if ( vm.count( "download-speed" ) > 0 )
+	{
 		agent.SetDownloadSpeed( vm["download-speed"].as<unsigned>() * 1000 );
+	}
+	else
+		agent.SetDownloadSpeed( 10000 * 1000 );
 
 	Drive drive( &syncer, config.GetAll() ) ;
 	drive.DetectChanges() ;
-- 
```
Test builds - Fedora:
http://goo.gl/Gm4ffO
drive/

**Comment by vitalif** [comment]
What's this? Does it fix the issue?

**Comment by cinquecento** [comment]
@vitalif
on Fedora, patch fixes issue #81

**Comment by vitalif** [comment]
Very interesting... O_o

**Comment by DarthSerious** [comment]
grive -U 10000 -D 10000
does the trick
Using Debian 8.5.0 jessie

PS: 
Installation difficulty which is apparently common in Debian with the APT Launchpad repository doesnt recognize "jessie", but will recognize the Ubuntu "trusty" source id.  So changed the  deb attributes in repository list:  /etc/apt/sources.list.d/nilarimogard-webupd8-jessie.list

deb http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu trusty main
deb-src http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu trusty main

**Comment by vitalif** [comment]
This is really strange because curl docs say that default and 0 equals to "unlimited"... https://curl.haxx.se/libcurl/c/CURLOPT_MAX_RECV_SPEED_LARGE.html

**Comment by vitalif** [comment]
Oh sorry it's very simple. I'm just not initializing mMaxUpload/mMaxDownload to 0 so it basically sets a random speed limit without -D and -U options. I'll fix it today

**Comment by vitalif** [comment]
Just committed the fix, check please

**Comment by cinquecento** [comment]
OK, commit fbf8f16 restores default transfer rate.
