### ISSUE TITLE
Security and Grive?

### ISSUE THREAD

**Issue by vx28643** [vitalif/grive2#84]
I am excited to find an open source Linux solution for Google Drive but before I grant Grive the required permissions, I'd like to better understand what I am agreeing to.

After running `grive -a` and copy/paste the url into my browser, google says:

```
grive would like to:

View your email address
View your basic profile info
View and manage your spreadsheets in Google Drive
View and manage any of your documents and files in Google Drive
```

Exactly what or who am I giving these permissions to? Is it only the instance of Grive running on my computer, or could this result in anyone else accessing my Google Drive and other info?

I'd like to understand exactly how it works, before using it.

Thanks.

**Comment by vitalif** [comment]
You're authorizing a single token, i.e. only a single instance of grive2... in fact even a single working directory.

**Comment by vx28643** [comment]
Thanks for your reply.

I assume you're saying that the authorization token is kept private by Grive2 - i.e. not sent anywhere and kept only on the local machine? If so, then can you please tell me where is the token stored on the local system, and is it in plain text or protected somehow?

(I am trying to get my answers by looking at the code however I don't have much experience with C++.)

**Comment by vitalif** [comment]
It's kept in plain text in .grive file inside your working directory

**Comment by vx28643** [comment]
Thanks for the answers!

**Comment by vx28643** [comment]
Apologies for re-opening. Just trying to gain a better understanding.

Why does Grive require the "email address" and "basic profile info" if it's only purpose is to sync the directories? Are these things required by the google drive API?

**Comment by vitalif** [comment]
I don't know, it's left from earlier versions & developers... in fact I think it's not required, here is the help page: https://developers.google.com/drive/v3/web/about-auth

I suppose "https://www.googleapis.com/auth/drive" scope should be sufficient. And maybe it requires another scope for google docs, however I'm not sure (there is experimental support for syncing google docs with grive2 in a branch)

**Comment by vx28643** [comment]
Thank you for providing that info. Much appreciated :) I'll try out Grive2 before asking more questions.
