### ISSUE TITLE
How to set a remote (Google) folder?

### ISSUE THREAD

**Issue by diman82** [vitalif/grive2#86]
Tried:
cd /opt/share/Grive
grive -p ./Grive -a

But it syncs my whole Google Drive!

_sync "./Grive/מסמכים שונים/תביעה כספית נגד שכנים על אי השתתפות בתשלום זיפות גג/KtavTviaaKaspit.doc" created in remote. creating local
sync "./Grive/מסמכים שונים/ערעור תעבורה בימש מחוזי חיפה.docx" created in remote. creating local
sync "./Grive/מסמכים שונים/בקשה למסירת החלטה בפקס - דואר.docx" created in remote. creating local
sync "./Grive/מסמכים שונים/בקשה דחופה לתיקון טעות סופר בתיק ערעור.docx" created in remote. creating local
sync "./Grive/מסמכים שונים/Default.rdp" created in remote. creating local
sync "./Grive/מסמכים שונים/מכתב סבא - ועידת תביעות.docx" created in remote. creating local
sync "./Grive/מסמכים שונים/בקשה לביטול פסק דין עקב מעשה בי-דין.docx" created in remote. creating local
sync "./Grive/מסמכים שונים/תצהיר דימה מדבדאב.doc" created in remote. creating local
sync "./Grive/SP2016RC" created in remote. creating local
sync "./Grive/SP2016RC/Windows Server 2012.part02.rar" created in remote. creating local
^C_

**Am I misdoing something?**

**Comment by vitalif** [comment]
Do you want to sync only a subdir of your gdrive? Use -s for it.

**Comment by diman82** [comment]
Great, please update the documentation/wiki, it isn't so clear that '-s' option relates to a gdrive remote folder.
