### ISSUE TITLE
sync not working when changes are applied

### ISSUE THREAD

**Issue by diman82** [vitalif/grive2#87]
Changed files both locally and on a remote folder on Gdrive, but grive doesn't pick the changes when I run again.

**1-st run:**
root@DD-WRT:/opt/share/Grive# grive -p /opt/share/Grive/ -s /Grive
Reading local directories
Reading remote server file list
Synchronizing files
sync "/opt/share/Grive/Grive" created in remote. creating local
sync "/opt/share/Grive/Grive/Непостижимый Дали.pps" created in remote. creating local
sync "/opt/share/Grive/Grive/P_20160704_230312.jpg" created in remote. creating local
sync "/opt/share/Grive/Grive/.grive" created in remote. creating local
Finished!

**Changes applied locally & remotely**
Please see the attached images.

![image](https://cloud.githubusercontent.com/assets/17273166/17179451/fb39a3c4-5421-11e6-89d8-ef7afde3ae3a.png)

**2-nd run:**
root@DD-WRT:/opt/share/Grive# grive -p /opt/share/Grive/ -s /Grive
Reading local directories
Reading remote server file list
Synchronizing files
sync "/opt/share/Grive/Grive/P_20160704_230312.jpg" deleted in remote. deleting local
Finished!

![image](https://cloud.githubusercontent.com/assets/17273166/17179608/82f19f24-5422-11e6-8b5a-09861a2f08a0.png)
![image](https://cloud.githubusercontent.com/assets/17273166/17179635/977ac22c-5422-11e6-80d4-aee526b88edf.png)

Several issues:

1. grive didn't catch the changes on the local drive and didn't upload or download new files to/from remote gdrive.
2. grive created a new folder 'Grive' inside already an existing one:  /opt/share/Grive/Grive

**Comment by vitalif** [comment]
> grive created a new folder 'Grive' inside already an existing one: /opt/share/Grive/Grive

-p = local root of the whole drive. -s = subdirectory INSIDE that root. running `grive -p dir` is the same as running `cd dir; grive`.

I.e. if you want to sync only /Grive folder of your google drive to /opt/share/Grive, you should run `grive -p /opt/share -s Grive`.

**Comment by vitalif** [comment]
However it's not good to run it like this because .grive and .grive_state will get placed in /opt/share

**Comment by vitalif** [comment]
So it's also correct if it didn't pick changes in /opt/share/Grive outside /opt/share/Grive/Grive :-)

**Comment by diman82** [comment]
Thanks for the clarification, it wasn't clear from the start :+1: )
