### ISSUE TITLE
dpkg-buildpackage warnings

### ISSUE THREAD

**Issue by D-sha** [vitalif/grive2#93]
Hi,
I received the following warnings while building the debian Grive2 package:

snip

dh_pysupport: This program is deprecated, you should use dh_python2 instead. Migration guide: http://deb.li/dhs2p

snip

dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/grive/usr/bin/grive was not linked against libexpat.so.1 (it uses none of the library's symbols)
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/grive/usr/bin/grive was not linked against libz.so.1 (it uses none of the library's symbols)
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/grive/usr/bin/grive was not linked against libboost_unit_test_framework.so.1.55.0 (it uses none of the library's symbols) 

snip

I intend to help out with the packaging when i get time. 
Is grive using these dependancies? Sorry i havent had time to check.

Thanks for your great work

**Comment by vitalif** [comment]
I think these are harmless. Expat was used in old "googledocs" API, the code is still there. unit_test_framework was used for tests (which are outdated now). zlib... I don't know who's using it, it's probably some peer dependency.

**Comment by vitalif** [comment]
Welcome in #112 if you want to help with getting this in debian. I'm closing the issue

**Comment by ikem-krueger** [comment]
Edit "debian/compat" and change the value from "7" to "9".
