### ISSUE TITLE
help with ignore command

### ISSUE THREAD

**Issue by saiballo** [vitalif/grive2#95]
Hi all,

I've a problem with --ignore parameter. This is my situation:

- FOLDER A
-- file x
-- file y
- FOLDER B
-- file x
-- file y
- FOLDER C

This is what I'm trying to do:

- want to exclude from sync the folder C
- want to exlclude from sync all files names "y" (they are in a folder)

I tried this command without success. Can someone help me please?

grive --ignore '^(C|(y))' -u

**Comment by vitalif** [comment]
grive --ignore '^C$|^C/|/y$' ("beginning C end OR beginning C/ OR /y END").

**Comment by saiballo** [comment]
thanks!
