### ISSUE TITLE
Fails to build in Ubuntu versions older than 16.10 (Yakkety Yak) after last commit

### ISSUE THREAD

**Issue by hotice** [vitalif/grive2#96]
After the last commit ( https://github.com/vitalif/grive2/commit/199a0500996bb3bb8b0349a28e996f269ee747e4 ), grive2 fails to build in Ubuntu versions older than 16.10 (Yakkety Yak). You can find the complete build log for Ubuntu 16.04 here (from my test PPA): https://launchpadlibrarian.net/282241364/buildlog_ubuntu-xenial-amd64.grive2_0.5.1-1+git20160902~webupd8~xenial0_BUILDING.txt.gz

**Comment by vitalif** [comment]
Ok I think it`s missing include... I'll fix it today

**Comment by marathone** [comment]
Doesn't completely build on Debian (Testing) either - something about signatures. Sorry didn't save the log. Gave me an executable, just not a .deb archive.

**Comment by vitalif** [comment]
did you look for packages in correct place? dpkg-buildpackage generates package in parent directory. "clearsign failed" is not an error, it's only indicating package signing is not set up

**Comment by D-sha** [comment]
@marathone add `-us -uc` to build without signing

**Comment by marathone** [comment]
Thanks fellas, got the package installed. Happy to see this project revived.
