### ISSUE TITLE
Segmentation fault bug when syncing

### ISSUE THREAD

**Issue by wcampospro** [vitalif/grive2#98]
Hi, when trying to sync my Grive it gives me a : _Segmentation fault (core dumped)_.

**uname -a:**
Linux archlnx 4.7.2-1-ARCH #1 SMP PREEMPT Sat Aug 20 23:02:56 CEST 2016 x86_64 GNU/Linux

I have Added the GDB backtrace below, thanks for the help.

**Running with GDB ->>**
Starting program: /usr/bin/grive 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff0d9a700 (LWP 16495)]
[Thread 0x7ffff0d9a700 (LWP 16495) exited]
Reading local directories
Reading remote server file list
[New Thread 0x7ffff0d9a700 (LWP 16532)]
[Thread 0x7ffff0d9a700 (LWP 16532) exited]

Thread 1 "grive" received signal SIGSEGV, Segmentation fault.
0x00000000004ab65b in gr::Resource::MD5[abi:cxx11]() const ()

Thanks again.

**Comment by vitalif** [comment]
> 0x00000000004ab65b in gr::Resource::MD5abi:cxx11 const ()
...and that's all???

**Comment by wcampospro** [comment]
Hi @vitalif, sorry but that's all the GDB gave me, if you can instruct me on how i can generate the details you need I'll be happy to append them.

Looking fwd to your response.

**Comment by vitalif** [comment]
very interesting... it shouldn't depend on the running kernel... (hardware issues?)
but ok... I'm closing this bug if you're saying you're not facing it anymore.
